# 4 - Principais Bibliotecas e Ferramentas Python para Aprendizado de Máquina 

## Atividade Prática 
---
A presente atividade prática tem como objetivo demonstrar o conteúdo aprendido em aula através de uma análise de ações da bolsa de valores extraídas de um arquivo `.csv` chamado `statusinvest-busca-avancada-28-06-2026.csv` presente no diretório deste _notebook_, o arquivo foi extraído do site de busca avançada do Status Invest disponível em [34].

No diretório onde se encontra este _jupyter notebook_ há um arquivo `requirements.txt` gerado através do comando `conda list -e > requirements.txt` [32] que pode ser utilizado para instalar as dependências do ambiente de desenvolvimento do `conda` utilizando o comando `conda install -f requirements.txt` [33].

In [1]:
import pandas as pd

# Extrai os dados do arquivo `csv` para inicializar o `DataFrame`.
# O arquivo utulizado é separado por `;` por isso configurado a incialização com `sep=';'`.
# Os valores decimais são separados por `,` por isso configurado a inicializaçãom com `decimal=','`
# Utilizado a coluna `TICKER` como index do `DataFrame` através da configuração `index_col='TICKER'`,
# a coluna `TICKER` representa o código do ativo. 
acoes = pd.read_csv('statusinvest-busca-avancada-28-06-2026.csv', sep=';', decimal=',', index_col='TICKER') 

# Visualização rápida do `DataFrame` utilizando o método `head`.
acoes.head()

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,PATRIMONIO / ATIVOS,PASSIVOS / ATIVOS,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO
TICKER,,,,,,,,,,,,,,,,,,,,,
AALR3,"2,79",NaN,"-5,28","0,40","0,14","26,83","9,47","-6,49","3,62","6,72",...,0.35,0.64,0.41,2.55,NaN,"111.745,33","7,00","-0,53","0,10","425.082.954,78"
ABCB4,"25,19",10.39,"6,52","0,92","0,10","15,81","14,70","12,20","5,41","5,41",...,0.11,0.89,0.12,28.96,24.19,"17.788.879,14","27,43","3,86","1,93","6.564.541.230,39"
ABEV3,"16,73",7.82,"16,93","2,93","1,85","51,48","26,87","17,66","11,13","10,43",...,0.63,0.36,0.62,8.61,6.48,"400.296.542,67","5,72","0,99","2,13","263.726.113.592,97"
ADHM3,"1,56",NaN,"-4,09","-1,29","105,12","100,00","-13.548,48","-18.860,61","-5,69","-5,69",...,-81.72,82.72,0.14,NaN,NaN,NaN,"-1,21","-0,38","-0,58","25.439.770,20"
AERI3,"2,08",NaN,"-0,14","-0,15","0,09","-6,13","-83,80","-147,32","-0,24","-3,71",...,-0.55,1.55,0.42,-19.51,NaN,"84.323,33","-13,47","-15,21","0,03","129.210.007,68"

In [2]:
acoes.info() # Informações da estrutura do `DataFrame` após inicialização.

<class 'pandas.DataFrame'>
Index: 617 entries, AALR3 to ZAMP3
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PRECO                   617 non-null    str
 1   DY                      283 non-null    float64
 2   P/L                     613 non-null    str
 3   P/VP                    613 non-null    str
 4   P/ATIVOS                613 non-null    str
 5   MARGEM BRUTA            585 non-null    str
 6   MARGEM EBIT             585 non-null    str
 7   MARG. LIQUIDA           585 non-null    str
 8   P/EBIT                  612 non-null    str
 9   EV/EBIT                 598 non-null    str
 10  DIVIDA LIQUIDA / EBIT   553 non-null    float64
 11  DIV. LIQ. / PATRI.      475 non-null    float64
 12  PSR                     580 non-null    str
 13  P/CAP. GIRO             608 non-null    str
 14  P. AT CIR. LIQ.         609 non-null    str
 15  LIQ. CORRENTE           588 non-null    str
 16  ROE                     614 non-null    str
 17  ROA                     614 non-null    str
 18  ROIC                    553 non-null    str
 19  PATRIMONIO / ATIVOS     614 non-null    float64
 20  PASSIVOS / ATIVOS       614 non-null    float64
 21  GIRO ATIVOS             614 non-null    float64
 22  CAGR RECEITAS 5 ANOS    566 non-null    float64
 23  CAGR LUCROS 5 ANOS      351 non-null    float64
 24   LIQUIDEZ MEDIA DIARIA  442 non-null    str
 25   VPA                    613 non-null    str
 26   LPA                    613 non-null    str
 27   PEG Ratio              612 non-null    str
 28   VALOR DE MERCADO       603 non-null    str
dtypes: float64(8), str(21)
memory usage: 144.6+ KB

In [3]:
# Função que formata os valores para float. Utilizada para converter diversas colunas do `DataFrame`
def str_to_float(str_value):
    # Como os valores vem com '.' para separar as unidades de milhar em diante e `,` para separar os centavos
    # essa `str` é tratada antes de ser transformada em `float`.
    str_value = str_value.replace('.', '')
    str_value = str_value.replace(',', '.')
    return float(str_value)

# Testando a função `str_to_float` com as possibilidades dentro do `DataFrame`
assert str_to_float('425.082.954,78') == 425082954.78
assert str_to_float('42,95') == 42.95
assert str_to_float('82') == 82
assert str_to_float('0.0') == 0

In [4]:
# Váriaveis para referencias o nome das colunas mais utilizadas
LIQUIDEZ_MEDIA_DIARIA = ' LIQUIDEZ MEDIA DIARIA'
LIQUIDEZ_MEDIA_DIARIA_FLOAT = 'LIQUIDEZ MEDIA DIARIA FLOAT'
VALOR_DE_MERCADO = ' VALOR DE MERCADO'
VALOR_DE_MERCADO_FLOAT = 'VALOR DE MERCADO FLOAT'
DY = 'DY'
P_L = 'P/L'
PRECO = 'PRECO'
VPA = ' VPA'
P_VP = 'P/VP'
acoes.columns

Index(['PRECO', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM BRUTA', 'MARGEM EBIT',
       'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT', 'DIVIDA LIQUIDA / EBIT',
       'DIV. LIQ. / PATRI.', 'PSR', 'P/CAP. GIRO', 'P. AT CIR. LIQ.',
       'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC', 'PATRIMONIO / ATIVOS',
       'PASSIVOS / ATIVOS', 'GIRO ATIVOS', 'CAGR RECEITAS 5 ANOS',
       'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA', ' VPA', ' LPA',
       ' PEG Ratio', ' VALOR DE MERCADO'],
      dtype='str')

In [5]:
# Como pode ser necessário a conversào de várias colunas foi criado uma função para isso.
def column_to_float(dataframe, column, new_column=None):
    """ 
    Recebe um `DataFrame` como primeiro parâmetro e em seguida o 
    nome da coluna que será convertida (`column`). 

    Caso informado o parâmetro `new_column` uma nova coluna é 
    adicionada ao `dataframe` se não a coluna convertida é sobreescrita.
        
    """
    if new_column is None :
        new_column = column

    # Poderia criar uma lógica que traz um novo `DataFrame` sem sobreescrever 
    # o informado, semelhante a regra do parâmetro `inplace` mas não é o caso.
    dataframe[new_column] = dataframe[column].apply(str_to_float)

    return dataframe

In [6]:
# Utilizaremos apenas registros que possui uma `LIQUIDEZ MEDIA DIARIA` que representa a média de liquidez do ativo
# nos últimos 30 dias [34]. 
acoes = acoes.dropna(subset=[LIQUIDEZ_MEDIA_DIARIA])

# Criado a coluna para representar a liquidez média diária em `float`.
# acoes[LIQUIDEZ_MEDIA_DIARIA_FLOAT] = acoes[LIQUIDEZ_MEDIA_DIARIA].apply(str_to_float)
column_to_float(acoes, LIQUIDEZ_MEDIA_DIARIA, LIQUIDEZ_MEDIA_DIARIA_FLOAT) # Manteve a coluna original para melhor visualização.

None # Apenas para não haver saida no jupyter e não poluir a visualização.

In [7]:
# Removendo ações que não possuem valor de mercado.

# Primeiro removendo valores nulos do `DataFrame` para não considerar ações que não possuem valor de mercado.
acoes = acoes.dropna(subset=[VALOR_DE_MERCADO])

# Criado a coluna para representar o valor de mercado em `float`.
# acoes[VALOR_DE_MERCADO_FLOAT] = acoes[VALOR_DE_MERCADO].apply(str_to_float)
column_to_float(acoes, VALOR_DE_MERCADO, VALOR_DE_MERCADO_FLOAT) # Manteve a coluna original para melhor visualização.

# Filtra por acoes que possuem valor de mercado maior que 0. 
acoes = acoes [acoes[VALOR_DE_MERCADO_FLOAT] > 0]

In [8]:
# Convertendo a coluna P/L para float.
# Convertido pois será utilizado a comparação com float mais a frente.
# acoes[P_L] = acoes[P_L].apply(str_to_float)
column_to_float(acoes, P_L)

None

In [9]:
# Convertendo a coluna preço para float para utilizar em comparações de resultados.
# acoes[PRECO] = acoes[PRECO].apply(str_to_float)
column_to_float(acoes, PRECO)

None

In [10]:
# Convertendo a coluna VPA para float para utilizar nos cálculos.
column_to_float(acoes, VPA)

None

In [11]:
# Convertendo coluna P/VP para ser utilizado em operações.
column_to_float(acoes, P_VP)

None

In [12]:
acoes.head() # Visualização do `DataFrame` após manipulação.

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT
TICKER,,,,,,,,,,,,,,,,,,,,,
AALR3,2.79,NaN,-5.28,0.40,"0,14","26,83","9,47","-6,49","3,62","6,72",...,0.41,2.55,NaN,"111.745,33",7.00,"-0,53","0,10","425.082.954,78",1.117453e+05,4.250830e+08
ABCB4,25.19,10.39,6.52,0.92,"0,10","15,81","14,70","12,20","5,41","5,41",...,0.12,28.96,24.19,"17.788.879,14",27.43,"3,86","1,93","6.564.541.230,39",1.778888e+07,6.564541e+09
ABEV3,16.73,7.82,16.93,2.93,"1,85","51,48","26,87","17,66","11,13","10,43",...,0.62,8.61,6.48,"400.296.542,67",5.72,"0,99","2,13","263.726.113.592,97",4.002965e+08,2.637261e+11
AERI3,2.08,NaN,-0.14,-0.15,"0,09","-6,13","-83,80","-147,32","-0,24","-3,71",...,0.42,-19.51,NaN,"84.323,33",-13.47,"-15,21","0,03","129.210.007,68",8.432333e+04,1.292100e+08
AESB3,8.12,NaN,-21.02,1.83,"0,42","27,29","23,39","-9,44","8,48","18,40",...,0.21,NaN,NaN,"13.684.494,00",4.43,"-0,39","2,77","8.367.914.180,36",1.368449e+07,8.367914e+09

In [13]:
acoes.info() # Mostrar as informações do `DataFrame` para melhor visualizar sua estrutura.

<class 'pandas.DataFrame'>
Index: 434 entries, AALR3 to ZAMP3
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   PRECO                        434 non-null    float64
 1   DY                           270 non-null    float64
 2   P/L                          434 non-null    float64
 3   P/VP                         434 non-null    float64
 4   P/ATIVOS                     434 non-null    str
 5   MARGEM BRUTA                 422 non-null    str
 6   MARGEM EBIT                  422 non-null    str
 7   MARG. LIQUIDA                422 non-null    str
 8   P/EBIT                       434 non-null    str
 9   EV/EBIT                      434 non-null    str
 10  DIVIDA LIQUIDA / EBIT        398 non-null    float64
 11  DIV. LIQ. / PATRI.           349 non-null    float64
 12  PSR                          418 non-null    str
 13  P/CAP. GIRO                  434 non-null    str
 14  P. AT CIR. LIQ.              433 non-null    str
 15  LIQ. CORRENTE                421 non-null    str
 16  ROE                          434 non-null    str
 17  ROA                          434 non-null    str
 18  ROIC                         398 non-null    str
 19  PATRIMONIO / ATIVOS          434 non-null    float64
 20  PASSIVOS / ATIVOS            434 non-null    float64
 21  GIRO ATIVOS                  434 non-null    float64
 22  CAGR RECEITAS 5 ANOS         415 non-null    float64
 23  CAGR LUCROS 5 ANOS           267 non-null    float64
 24   LIQUIDEZ MEDIA DIARIA       434 non-null    str
 25   VPA                         434 non-null    float64
 26   LPA                         434 non-null    str
 27   PEG Ratio                   433 non-null    str
 28   VALOR DE MERCADO            434 non-null    str
 29  LIQUIDEZ MEDIA DIARIA FLOAT  434 non-null    float64
 30  VALOR DE MERCADO FLOAT       434 non-null    float64
dtypes: float64(14), str(17)
memory usage: 108.5+ KB

In [14]:
# Podemos observar as dez empresas com o maior valor de mercado utilizando o `sort_values`
acoes.sort_values(by=VALOR_DE_MERCADO_FLOAT, ascending=False).head(10)

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT
TICKER,,,,,,,,,,,,,,,,,,,,,
GOLL54,9.75,NaN,-68484.87,-5256.20,"3.349,30","27,24","8,33","-5,90","48.540,32","6.379,51",...,0.83,28.24,NaN,"20.388,00",0.00,"0,00","872,51","11.732.704.010.232,77",2.038800e+04,1.173270e+13
PETR4,38.06,6.94,4.56,1.10,"0,39","47,36","28,88","21,60","3,41","5,88",...,0.40,12.83,72.19,"1.506.439.883,91",34.54,"8,35","0,04","521.728.118.374,24",1.506440e+09,5.217281e+11
PETR3,42.25,5.48,5.06,1.22,"0,44","47,36","28,88","21,60","3,79","5,88",...,0.40,12.83,72.19,"425.785.247,10",34.54,"8,35","0,04","521.728.118.374,24",4.257852e+08,5.217281e+11
ITUB3,44.38,7.09,10.64,2.33,"0,15","35,55","12,88","11,83","9,77","9,54",...,0.12,17.38,19.47,"255.308.787,71",19.02,"4,17","1,06","477.796.924.640,86",2.553088e+08,4.777969e+11
ITUB4,42.24,7.45,10.13,2.22,"0,15","35,55","12,88","11,83","9,30","9,54",...,0.12,17.38,19.47,"1.126.091.774,24",19.02,"4,17","1,01","477.796.924.640,86",1.126092e+09,4.777969e+11
VALE3,78.15,7.01,22.23,1.81,"0,76","35,08","15,71","7,26","10,28","12,38",...,0.47,0.72,-10.20,"1.281.504.147,71",43.07,"3,51","-0,44","346.920.335.556,60",1.281504e+09,3.469203e+11
ABEV3,16.73,7.82,16.93,2.93,"1,85","51,48","26,87","17,66","11,13","10,43",...,0.62,8.61,6.48,"400.296.542,67",5.72,"0,99","2,13","263.726.113.592,97",4.002965e+08,2.637261e+11
BPAC5,18.33,2.27,12.16,2.74,"0,25","21,43","29,09","26,78","11,20","11,13",...,0.08,16.36,39.92,"302.662,43",6.69,"1,51","0,22","212.628.556.350,52",3.026624e+05,2.126286e+11
BPAC3,22.88,1.82,15.18,3.42,"0,31","21,43","29,09","26,78","13,98","11,13",...,0.08,16.36,39.92,"474.185,29",6.69,"1,51","0,27","212.628.556.350,52",4.741853e+05,2.126286e+11
BPAC11,54.66,2.28,12.09,2.72,"0,25","21,43","29,09","26,78","11,13","11,13",...,0.08,16.36,39.92,"535.613.119,19",20.08,"4,52","0,22","212.628.556.350,52",5.356131e+08,2.126286e+11

In [15]:
## Podemos observar as empresas com maior liquidez média diária também
acoes.sort_values(by=LIQUIDEZ_MEDIA_DIARIA_FLOAT, ascending=False).head(10)

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT
TICKER,,,,,,,,,,,,,,,,,,,,,
PETR4,38.06,6.94,4.56,1.10,"0,39","47,36","28,88","21,60","3,41","5,88",...,0.40,12.83,72.19,"1.506.439.883,91",34.54,"8,35","0,04","521.728.118.374,24",1.506440e+09,5.217281e+11
VALE3,78.15,7.01,22.23,1.81,"0,76","35,08","15,71","7,26","10,28","12,38",...,0.47,0.72,-10.20,"1.281.504.147,71",43.07,"3,51","-0,44","346.920.335.556,60",1.281504e+09,3.469203e+11
ITUB4,42.24,7.45,10.13,2.22,"0,15","35,55","12,88","11,83","9,30","9,54",...,0.12,17.38,19.47,"1.126.091.774,24",19.02,"4,17","1,01","477.796.924.640,86",1.126092e+09,4.777969e+11
B3SA3,14.92,4.06,15.19,4.12,"1,55","90,46","60,27","42,49","10,71","10,62",...,0.24,3.58,3.60,"627.088.298,14",3.62,"0,98","3,22","75.293.780.000,00",6.270883e+08,7.529378e+10
BPAC11,54.66,2.28,12.09,2.72,"0,25","21,43","29,09","26,78","11,13","11,13",...,0.08,16.36,39.92,"535.613.119,19",20.08,"4,52","0,22","212.628.556.350,52",5.356131e+08,2.126286e+11
PRIO3,53.29,NaN,17.95,1.75,"0,73","25,55","18,08","14,65","14,55","22,09",...,0.28,52.26,41.73,"497.774.023,05",30.52,"2,97","-0,23","46.495.272.565,27",4.977740e+08,4.649527e+10
AXIA3,55.62,6.56,17.16,1.35,"0,58","47,02","15,92","21,89","23,60","30,52",...,0.16,7.26,8.52,"497.690.698,95",41.16,"3,24","-10,68","165.886.326.463,00",4.976907e+08,1.658863e+11
ITSA4,13.46,9.74,8.89,1.67,"1,32","25,32","221,97","203,02","8,13","8,37",...,0.07,7.01,19.20,"490.901.476,57",8.04,"1,51","0,77","151.090.370.294,18",4.909015e+08,1.510904e+11
BBDC4,17.92,6.81,8.08,1.06,"0,08","27,28","7,91","8,15","8,33","7,80",...,0.12,22.38,7.93,"486.776.372,86",16.97,"2,22","0,34","177.716.030.161,08",4.867764e+08,1.777160e+11
BBAS3,20.34,2.71,7.42,0.61,"0,04","30,81","1,95","4,82","18,34","18,34",...,0.12,26.49,3.40,"431.498.858,24",33.45,"2,74","-0,20","116.565.164.373,60",4.314989e+08,1.165652e+11

In [16]:
# Caso esteja procurando por empresas com determinado DY (Dividend Yield: Indicador utilizado para relacionar
# os proventos pagos por uma companhia e preço atual de suas ações). 
# Digamos que procuramos empresas com DY entre 8% e 15% inclusivo. 
acoes[ (acoes[DY] >= 8) & (acoes[DY] <= 15) ].head(10)

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,GIRO ATIVOS,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT
TICKER,,,,,,,,,,,,,,,,,,,,,
ABCB4,25.19,10.39,6.52,0.92,"0,10","15,81","14,70","12,20","5,41","5,41",...,0.12,28.96,24.19,"17.788.879,14",27.43,"3,86","1,93","6.564.541.230,39",1.778888e+07,6.564541e+09
ALOS3,28.04,9.80,17.08,1.09,"0,57","73,41","52,49","28,81","9,37","7,94",...,0.12,29.09,37.40,"154.560.152,48",25.71,"1,64","-4,29","14.137.514.153,88",1.545602e+08,1.413751e+10
AZZA3,18.99,13.04,4.71,0.49,"0,26","54,89","8,66","7,17","3,90","6,07",...,0.76,49.34,76.49,"52.243.110,05",38.77,"4,03","0,04","3.921.241.548,87",5.224311e+07,3.921242e+09
BBSE3,39.17,11.61,8.27,6.02,"3,88",NaN,NaN,NaN,"7,60","7,60",...,0.00,NaN,19.01,"272.326.264,62",6.51,"4,74","1,31","76.044.638.000,00",2.723263e+08,7.604464e+10
BEES3,8.50,8.42,9.06,1.20,"0,07","28,49","5,93","5,76","8,80","8,88",...,0.14,28.74,8.03,"70.156,62",7.08,"0,94","-0,29","2.979.936.553,88",7.015662e+04,2.979937e+09
BEES4,8.78,8.30,9.36,1.24,"0,08","28,49","5,93","5,76","9,09","8,88",...,0.14,28.74,8.03,"25.779,24",7.08,"0,94","-0,30","2.979.936.553,88",2.577924e+04,2.979937e+09
BGIP4,32.56,13.82,4.69,0.77,"0,06","31,02","13,02","8,21","2,96","3,86",...,0.15,24.17,24.15,"16.640,90",42.07,"6,94","0,76","980.858.541,30",1.664090e+04,9.808585e+08
BLAU3,10.22,9.03,9.78,1.04,"0,67","40,44","18,65","13,82","7,24","7,30",...,0.49,7.57,-0.84,"2.300.920,33",9.84,"1,05","-1,08","2.383.427.876,62",2.300920e+06,2.383428e+09
BMGB4,5.30,10.32,5.80,0.69,"0,07","33,14","3,52","6,79","11,17","11,17",...,0.17,16.75,13.57,"4.943.369,43",7.68,"0,91","0,05","3.435.903.588,80",4.943369e+06,3.435904e+09
BMOB3,23.51,9.08,12.60,2.07,"0,99","26,29","8,83","8,91","12,73","10,78",...,0.88,58.14,34.91,"8.605.833,05",11.38,"1,87","0,52","2.012.653.295,92",8.605833e+06,2.012653e+09

Agora para fazer uma análise desses ativos com base em algumas das regras definidas pelo investidor Graham em [35] com objetivo de mostrar análises que podem ser úteis através das possibilidades que a biblioteca Pandas propõem.
1. Valor de mercado acima de 2 bi.
2. PL não pode ser superior a 15
3. Preço atual não ser maior que 1,5 * VPA.
4. PL * P/VP nao pode ser maior que 22,5

As regras escolhidas tem como objetivo mostrar as análises que pode ser feitas com base nas informações que temos no `DataFrame` a partir de um conceito apresentado, existem outras regras a respeito da escolha inicial de ativos que também devem ser consideras mas não são contempladas nesta análise de exemplo.

In [17]:
graham = acoes.copy() # Copiamos o `DataFrame` para manter o `acoes` na forma tratada para ser usado por outras
                        # análises.

In [18]:
# 1. Valor de mercado acima de 2 bi.
# Para isso basta filtrar o valor de mercado
graham = acoes[ acoes[VALOR_DE_MERCADO_FLOAT] > 2000000000 ] 
print(f'Quantidade de Ativos: {len(graham)}') # Apenas para mostrar a quantidade de ações na análise.

Quantidade de Ativos: 226

In [19]:
# 2. PL nao pode ser superior a 15
# Para isso filtramos o P/L para apenas valores menores ou iguais a 15.
graham = graham[ graham[P_L] <= 15 ]
print(f'Quantidade de Ativos: {len(graham)}')

Quantidade de Ativos: 164

In [20]:
# 3. Preço atual não ser maior que 1.5 * VPA (P>1.5*VPA)
# Primeiro calculamos a equação de VPA * 1.5 em seguida comparamos se o preço é menor ou igual ao resultado.
graham = graham[ (graham[VPA] * 1.5) <= graham[PRECO] ]
print(f'Quantidade de Ativos: {len(graham)}')

Quantidade de Ativos: 77

In [21]:
# 4. PL * P/VP nao pode ser maior que 22,5
# De forma semelhante a regra três realiza-se o cálculo e em seguida seu valor é comparado conforme.
# A fim de ordenar os ativos por P/L * P/VP será adicionado a coluna `'PL_X_PVP'` no `DataFrame` armazenando o
# resultado da operação.
graham['PL_X_PVP'] = graham[P_L] * graham[P_VP]

# Comparado o resultado.
graham = graham[ graham['PL_X_PVP'] <= 22.5 ] 

# Mostramos o resultado ordenado.
# Ao mostrar o resultado foi observado que há resultados negativos, esses resultados serão removidos. 
graham = graham[ graham['PL_X_PVP'] > 0 ]

print(f'Quantidade de Ativos: {len(graham)}')
graham.sort_values(by='PL_X_PVP', ascending=False).head(10)

Quantidade de Ativos: 41

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,CAGR RECEITAS 5 ANOS,CAGR LUCROS 5 ANOS,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT,PL_X_PVP
TICKER,,,,,,,,,,,,,,,,,,,,,
ITUB4,42.24,7.45,10.13,2.22,"0,15","35,55","12,88","11,83","9,30","9,54",...,17.38,19.47,"1.126.091.774,24",19.02,"4,17","1,01","477.796.924.640,86",1.126092e+09,4.777969e+11,22.4886
ENMT4,36.45,7.22,10.93,2.04,"0,47","24,72","17,96","7,84","4,77","9,40",...,12.00,1.50,"56.265,29",17.86,"3,34","-0,40","7.937.381.705,37",5.626529e+04,7.937382e+09,22.2972
FLRY3,15.61,6.91,13.46,1.65,"0,64","26,61","14,77","7,47","6,80","9,36",...,22.78,19.83,"27.777.408,32",9.47,"1,16","11,63","8.541.651.915,86",2.777741e+07,8.541652e+09,22.2090
ENMT3,35.88,7.34,10.76,2.01,"0,47","24,72","17,96","7,84","4,70","9,40",...,12.00,1.50,"105.571,76",17.86,"3,34","-0,39","7.937.381.705,37",1.055718e+05,7.937382e+09,21.6276
FIQE3,5.87,11.32,10.51,2.00,"0,77","51,33","28,14","17,91","6,69","7,60",...,32.89,34.61,"3.138.443,10",2.93,"0,56","0,37","2.342.638.612,02",3.138443e+06,2.342639e+09,21.0200
CEBR5,25.17,15.66,10.87,1.92,"1,33","43,60","43,01","34,89","8,82","7,99",...,14.87,-17.34,"95.668,95",13.12,"2,32","-1,46","2.025.780.368,10",9.566895e+04,2.025780e+09,20.8704
PSSA3,53.26,5.66,9.35,2.22,"0,60","100,00","7,63","8,81","10,79","6,70",...,17.03,16.88,"63.214.336,38",24.03,"5,70","0,31","34.437.173.555,60",6.321434e+07,3.443717e+10,20.7570
ALPA3,9.75,5.04,10.75,1.93,"1,06","52,49","14,46","13,17","9,79","11,86",...,6.29,34.59,"92.989,86",5.06,"0,91","0,05","7.587.445.803,60",9.298986e+04,7.587446e+09,20.7475
BRFS3,17.95,11.62,10.21,2.01,"0,43","24,77","9,54","4,32","4,62","6,96",...,10.51,15.13,"377.952.894,00",8.93,"1,76","-0,38","28.579.854.639,05",3.779529e+08,2.857985e+10,20.5221
CPFE3,45.50,8.21,9.10,2.16,"0,62","31,30","24,50","12,79","4,75","7,10",...,7.50,9.61,"70.126.721,91",21.09,"5,00","1,13","52.427.577.020,00",7.012672e+07,5.242758e+10,19.6560

Agora filtraremos os ativos com base em uma regra definida por Bazin em [36] com o mesmo objetivo do filtro
anterior. A regra é a seguinte:
1. O Preço da ação pode ser no máximo 16,67 vezes o valor do dividendo.

Esse segundo `DataFrame` (`bazin`) será utilizado em conjunto do `graham` para que seja feito uma interseção
dos ativos que estão contemplados em ambas as regras, a fim de mostrar outras funcionalidades ensinadas nas 
aulas.

In [22]:
bazin = acoes.copy() # Copiamos o `DataFrame` para manter o `acoes` na forma tratada para ser usado por outras
                        # análises.

In [23]:
# Primeiro pegamos o valor do dividendo de forma hipotética multiplicando o `DY` pelo `PRECO` e adicionamos na coluna
# Dividendo.
# Primeiro removemos as linhas que não possuem `DY`.
bazin.dropna(subset=DY, inplace=True)

# Poderia fazer essa operação no próprio `DataFrame` `graham` mas a o objetivo e juntar as informações de duas fontes de dados.
bazin['DIVIDENDO'] = (bazin[DY] / 100 ) * bazin [PRECO] # Divide por 100 antes da multiplicação pois `DY` é uma porcentagem.

# Agora definimos o preço máximo permitido segunda a regra multiplicando o `DIVIDENDO` por 16.67
bazin['PRECO_MAXIMO'] = bazin['DIVIDENDO'] * 16.67

# Por fim basta filtrar comparando onde o `PRECO` é menor ou igual o `PRECO_MAXIMO` calculado.
bazin = bazin[ bazin['PRECO'] <= bazin['PRECO_MAXIMO'] ]

print(f'Quantidade de Ativos: {len(bazin)}')

# Para visualzação vamos ordenar pelos preços que possuem a maior diferença em relação ao preço máximo.
# Para isso vamos criar uma nova coluna chamada `DIFF_PRECO_MAXIMO` onde "DIFF" signifca diferença.
bazin['DIFF_PRECO_MAXIMO'] = bazin['PRECO_MAXIMO'] - bazin['PRECO']

bazin.sort_values(by='DIFF_PRECO_MAXIMO', ascending=False).head(10)

Quantidade de Ativos: 134

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,LIQUIDEZ MEDIA DIARIA,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT,DIVIDENDO,PRECO_MAXIMO,DIFF_PRECO_MAXIMO
TICKER,,,,,,,,,,,,,,,,,,,,,
BMKS3,389.99,33.35,2.98,0.86,"0,71","28,02","-188,07","445,49","-7,05","-0,59",...,"15.641,43",454.44,"130,97","0,01","177.347.952,50",15641.43,1.773480e+08,130.061665,2168.127956,1778.137956
MOAR3,61.21,20.64,23.51,0.81,"0,34",NaN,NaN,NaN,"-11,73","-4,93",...,"0,00",75.49,"2,60","-0,28","749.897.237,41",0.00,7.498972e+08,12.633744,210.604512,149.394512
BAZA3,59.99,19.91,3.98,0.47,"0,05","1,10","6,05","12,73","8,38","8,38",...,"442.043,77",128.13,"15,08","-0,13","3.362.938.316,85",442043.77,3.362938e+09,11.944009,199.106630,139.116630
UNIP6,59.71,17.05,18.03,3.61,"0,91","25,68","12,43","7,48","10,85","14,63",...,"9.589.500,23",16.55,"3,31","-0,42","6.704.454.212,27",9589500.23,6.704454e+09,10.180555,169.709852,109.999852
UNIP5,60.51,16.82,18.28,3.66,"0,92","25,68","12,43","7,48","11,00","14,63",...,"8.349,06",16.55,"3,31","-0,43","6.704.454.212,27",8349.06,6.704454e+09,10.177782,169.663626,109.153626
TKNO3,214.99,9.00,21.11,2.19,"1,79","21,26","10,82","10,11","19,72","18,66",...,"0,00",98.12,"10,18","-0,52","635.123.987,99",0.00,6.351240e+08,19.349100,322.549497,107.559497
SCAR3,12.40,57.26,15.97,0.69,"0,25","46,94","18,55","15,76","13,57","22,36",...,"237.394,29",17.99,"0,78","-0,06","715.942.755,60",237394.29,7.159428e+08,7.100240,118.361001,105.961001
SOND3,38.66,22.14,2.81,1.33,"0,73","35,67","19,63","14,61","2,09","2,58",...,"3.866,00",29.12,"13,78","0,07","161.212.922,00",3866.00,1.612129e+08,8.559324,142.683931,104.023931
CGAS5,123.90,10.75,10.67,9.54,"1,00","32,89","28,19","14,41","5,45","8,38",...,"161.782,33",12.99,"11,62","-0,86","16.697.593.962,00",161782.33,1.669759e+10,13.319250,222.031898,98.131898
UNIP3,58.35,15.86,17.62,3.53,"0,89","25,68","12,43","7,48","10,60","14,63",...,"326.256,67",16.55,"3,31","-0,42","6.704.454.212,27",326256.67,6.704454e+09,9.254310,154.269348,95.919348

In [24]:
# Agora com dois conjuntos de regras observamos quais os ativos que atendem ambos requisitos.

# Para isso podemos fazer o `merge` `inner` entre ambos os `DataFrames` através do indíce (`TICKER`)
# Para não adicionar colunas repetidas no `DataFrame` selecionamos apenas as colunas adicionais do `DataFrame` `bazin`.
analise = graham.merge(bazin[ ['DIVIDENDO', 'PRECO_MAXIMO', 'DIFF_PRECO_MAXIMO'] ], on='TICKER')

# Informações do `DataFrame` final.
analise.info()

<class 'pandas.DataFrame'>
Index: 21 entries, BRFS3 to VULC3
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   PRECO                        21 non-null     float64
 1   DY                           21 non-null     float64
 2   P/L                          21 non-null     float64
 3   P/VP                         21 non-null     float64
 4   P/ATIVOS                     21 non-null     str
 5   MARGEM BRUTA                 21 non-null     str
 6   MARGEM EBIT                  21 non-null     str
 7   MARG. LIQUIDA                21 non-null     str
 8   P/EBIT                       21 non-null     str
 9   EV/EBIT                      21 non-null     str
 10  DIVIDA LIQUIDA / EBIT        18 non-null     float64
 11  DIV. LIQ. / PATRI.           18 non-null     float64
 12  PSR                          21 non-null     str
 13  P/CAP. GIRO                  21 non-null     str
 14  P. AT CIR. LIQ.              21 non-null     str
 15  LIQ. CORRENTE                21 non-null     str
 16  ROE                          21 non-null     str
 17  ROA                          21 non-null     str
 18  ROIC                         18 non-null     str
 19  PATRIMONIO / ATIVOS          21 non-null     float64
 20  PASSIVOS / ATIVOS            21 non-null     float64
 21  GIRO ATIVOS                  21 non-null     float64
 22  CAGR RECEITAS 5 ANOS         21 non-null     float64
 23  CAGR LUCROS 5 ANOS           18 non-null     float64
 24   LIQUIDEZ MEDIA DIARIA       21 non-null     str
 25   VPA                         21 non-null     float64
 26   LPA                         21 non-null     str
 27   PEG Ratio                   21 non-null     str
 28   VALOR DE MERCADO            21 non-null     str
 29  LIQUIDEZ MEDIA DIARIA FLOAT  21 non-null     float64
 30  VALOR DE MERCADO FLOAT       21 non-null     float64
 31  PL_X_PVP                     21 non-null     float64
 32  DIVIDENDO                    21 non-null     float64
 33  PRECO_MAXIMO                 21 non-null     float64
 34  DIFF_PRECO_MAXIMO            21 non-null     float64
dtypes: float64(18), str(17)
memory usage: 5.9+ KB

In [25]:
analise # Por ser poucas linhas o `notebook` renderizou todo o `DataFrame` mas podemos selecionar a quantidade total

analise.head(len(analise))

,PRECO,DY,P/L,P/VP,P/ATIVOS,MARGEM BRUTA,MARGEM EBIT,MARG. LIQUIDA,P/EBIT,EV/EBIT,...,VPA,LPA,PEG Ratio,VALOR DE MERCADO,LIQUIDEZ MEDIA DIARIA FLOAT,VALOR DE MERCADO FLOAT,PL_X_PVP,DIVIDENDO,PRECO_MAXIMO,DIFF_PRECO_MAXIMO
TICKER,,,,,,,,,,,,,,,,,,,,,
BRFS3,17.95,11.62,10.21,2.01,"0,43","24,77","9,54","4,32","4,62","6,96",...,8.93,"1,76","-0,38","28.579.854.639,05",3.779529e+08,2.857985e+10,20.5221,2.085790,34.770119,16.820119
CEBR5,25.17,15.66,10.87,1.92,"1,33","43,60","43,01","34,89","8,82","7,99",...,13.12,"2,32","-1,46","2.025.780.368,10",9.566895e+04,2.025780e+09,20.8704,3.941622,65.706839,40.536839
CPFE3,45.50,8.21,9.10,2.16,"0,62","31,30","24,50","12,79","4,75","7,10",...,21.09,"5,00","1,13","52.427.577.020,00",7.012672e+07,5.242758e+10,19.6560,3.735550,62.271619,16.771619
ENMT3,35.88,7.34,10.76,2.01,"0,47","24,72","17,96","7,84","4,70","9,40",...,17.86,"3,34","-0,39","7.937.381.705,37",1.055718e+05,7.937382e+09,21.6276,2.633592,43.901979,8.021979
ENMT4,36.45,7.22,10.93,2.04,"0,47","24,72","17,96","7,84","4,77","9,40",...,17.86,"3,34","-0,40","7.937.381.705,37",5.626529e+04,7.937382e+09,22.2972,2.631690,43.870272,7.420272
FIQE3,5.87,11.32,10.51,2.00,"0,77","51,33","28,14","17,91","6,69","7,60",...,2.93,"0,56","0,37","2.342.638.612,02",3.138443e+06,2.342639e+09,21.0200,0.664484,11.076948,5.206948
FLRY3,15.61,6.91,13.46,1.65,"0,64","26,61","14,77","7,47","6,80","9,36",...,9.47,"1,16","11,63","8.541.651.915,86",2.777741e+07,8.541652e+09,22.2090,1.078651,17.981112,2.371112
ITSA3,13.50,9.80,8.91,1.68,"1,32","25,32","221,97","203,02","8,15","8,37",...,8.04,"1,51","0,77","151.090.370.294,18",1.225890e+06,1.510904e+11,14.9688,1.323000,22.054410,8.554410
ITSA4,13.46,9.74,8.89,1.67,"1,32","25,32","221,97","203,02","8,13","8,37",...,8.04,"1,51","0,77","151.090.370.294,18",4.909015e+08,1.510904e+11,14.8463,1.311004,21.854437,8.394437
ITUB4,42.24,7.45,10.13,2.22,"0,15","35,55","12,88","11,83","9,30","9,54",...,19.02,"4,17","1,01","477.796.924.640,86",1.126092e+09,4.777969e+11,22.4886,3.146880,52.458490,10.218490
LAVV3,11.94,21.55,5.88,1.71,"0,50","33,83","25,07","22,06","5,17","6,23",...,7.00,"2,03","0,56","2.333.486.162,88",4.137530e+06,2.333486e+09,10.0548,2.573070,42.893077,30.953077
MILS3,15.49,6.86,8.44,2.04,"0,84","61,90","35,43","22,79","5,43","7,15",...,7.59,"1,84","0,17","3.628.356.858,89",1.535132e+07,3.628357e+09,17.2176,1.062614,17.713775,2.223775
PINE3,11.90,6.87,5.79,1.78,"0,09","20,91","15,46","10,22","3,82","3,82",...,6.67,"2,06","0,01","3.090.433.070,20",5.357900e+04,3.090433e+09,10.3062,0.817530,13.628225,1.728225
PINE4,12.00,6.82,5.84,1.80,"0,09","20,91","15,46","10,22","3,86","3,82",...,6.67,"2,06","0,01","3.090.433.070,20",1.445727e+07,3.090433e+09,10.5120,0.818400,13.642728,1.642728
POMO3,5.50,18.73,5.51,1.69,"0,72","25,49","15,36","13,81","4,95","6,27",...,3.25,"1,00","0,54","7.154.075.733,85",4.048544e+06,7.154076e+09,9.3119,1.030150,17.172601,11.672601
POMO4,5.85,17.61,5.86,1.80,"0,77","25,49","15,36","13,81","5,27","6,27",...,3.25,"1,00","0,57","7.154.075.733,85",4.125769e+07,7.154076e+09,10.5480,1.030185,17.173184,11.323184
TAEE11,39.72,8.25,8.72,1.72,"0,59","54,77","57,40","33,52","5,10","8,85",...,23.10,"4,55","-1,26","13.683.496.586,04",4.715575e+07,1.368350e+10,14.9984,3.276900,54.625923,14.905923
TAEE3,13.18,8.28,8.69,1.71,"0,59","54,77","57,40","33,52","5,07","8,85",...,7.70,"1,52","-1,25","13.683.496.586,04",1.143927e+06,1.368350e+10,14.8599,1.091304,18.192038,5.012038
TAEE4,13.33,8.20,8.78,1.73,"0,59","54,77","57,40","33,52","5,13","8,85",...,7.70,"1,52","-1,27","13.683.496.586,04",1.866292e+06,1.368350e+10,15.1894,1.093060,18.221310,4.891310
TGMA3,30.44,12.62,8.44,2.21,"1,47","18,59","14,12","10,32","6,17","6,19",...,13.80,"3,61","-0,61","2.009.128.732,60",4.645732e+06,2.009129e+09,18.6524,3.841528,64.038272,33.598272
VULC3,14.40,32.67,4.02,1.83,"1,14","41,06","20,92","31,34","6,02","6,90",...,7.88,"3,58","0,04","4.578.943.248,00",1.312000e+07,4.578943e+09,7.3566,4.704480,78.423682,64.023682