# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos em um arquivo `.csv` final que 
será utilizado para programar o modelo.

In [1]:
import pandas as pd

PATH_DIRETORIO = 'dados/bkp/final_08/'

A seguir foram lidos os arquivos `.csv` e mesclados (_merge_) utilizando 
Pandas.

In [2]:
PATH_ARQUIVO_MUSICAS_PONTUACAO = PATH_DIRETORIO + 'kworb/transformacao/musicas_pontuacao_anual.csv'

musicas_pontuacao = pd.read_csv(PATH_ARQUIVO_MUSICAS_PONTUACAO, sep=';', decimal='.')

musicas_pontuacao.tail(3)

,id_musica,musica,media_pontos,media_pts_ganho,total_pts_calc
3928,01a02706-e02d-72a8-bbbd-06429371d930,第三个吻痕,1059.0,1059.0,0.002
3929,01a02706-e02d-72a8-bbbd-0643200f6822,Please love yourself(请好好爱自己),1194.5,303.5,0.022
3930,01a02706-e02d-72a8-bbbd-0644229abe54,Genesis HE★VENS,858.0,136.0,0.005

In [3]:
PATH_ARQUIVO_MUSICAS_GENERO_0_1 = PATH_DIRETORIO + 'musicbrainz/transformacao/musicas_generos_0_1.csv'

musicas_generos_0_1 = pd.read_csv(PATH_ARQUIVO_MUSICAS_GENERO_0_1, sep=';', decimal=',')

musicas_generos_0_1.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,rap rock,celtic new age,glam metal,pop metal,gothic,gothic rock,progressive metal,rap metal,future rave,hands up
238,01a02706-e028-7424-9d5e-123e77a3b087,pop|pop rock,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
239,01a02706-e028-7424-9d5e-1246b72dec8a,folk|folk rock|indie pop|pop|pop rock|rock|sof...,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
240,01a02706-e028-7424-9d5e-1249c3c780cd,hip hop|pop rap|trap,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dados_musicas = pd.merge(left=musicas_generos_0_1, right=musicas_pontuacao, on='id_musica')

dados_musicas.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,gothic,gothic rock,progressive metal,rap metal,future rave,hands up,musica,media_pontos,media_pts_ganho,total_pts_calc
238,01a02706-e028-7424-9d5e-123e77a3b087,pop|pop rock,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,Vindaloo,1236.0,574.0,0.244
239,01a02706-e028-7424-9d5e-1246b72dec8a,folk|folk rock|indie pop|pop|pop rock|rock|sof...,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,My Moon My Man,1027.0,535.0,0.011
240,01a02706-e028-7424-9d5e-1249c3c780cd,hip hop|pop rap|trap,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Trap Queen,1364.5,174.5,1.884

In [5]:


colunas = list(dados_musicas.columns)

colunas_ordenadas = colunas[:2] + colunas[-4:] + colunas[2:-4]

colunas_ordenadas

['id_musica',
 'generos',
 'musica',
 'media_pontos',
 'media_pts_ganho',
 'total_pts_calc',
 'electro',
 'electronic',
 'pop',
 'alternative metal',
 'alternative rock',
 'heavy metal',
 'pop rock',
 'post-grunge',
 'rock',
 'southern rock',
 'arena rock',
 'funk',
 'grunge',
 'hard rock',
 'house',
 'soft rock',
 'symphonic rock',
 'reggae',
 'dance',
 'dance-pop',
 'disco',
 'euro-disco',
 'europop',
 'synth-pop',
 'ballad',
 'christmas music',
 'schlager',
 'acid jazz',
 'blues',
 'blues rock',
 'classic rock',
 'metal',
 'rock and roll',
 'power metal',
 'thrash metal',
 'soul',
 'progressive rock',
 'classic country',
 'contemporary country',
 'country',
 'neo-traditional country',
 'singer-songwriter',
 'alternative r&b',
 'folk pop',
 'gospel',
 'pop soul',
 'stomp and holler',
 'alternative dance',
 'dance-rock',
 'euro house',
 'new romantic',
 'new wave',
 'post-punk',
 'sophisti-pop',
 'brill building',
 'club',
 'contemporary jazz',
 'contemporary r&b',
 'jazz',
 'jazz pop',
 'motown',
 'neo soul',
 'r&b',
 'soul jazz',
 'vocal jazz',
 'power pop',
 'afrobeat',
 'indie pop',
 'indie rock',
 'bubblegum dance',
 'bubblegum pop',
 'eurodance',
 'trance',
 'tribal house',
 'new jack swing',
 'aor',
 'dancehall',
 'festival progressive house',
 'progressive house',
 'pop rap',
 'trap',
 'k-pop',
 'alternative pop',
 'boom bap',
 'synth funk',
 'experimental hip hop',
 'jersey club rap',
 'electropop',
 'drone',
 'reductionism',
 'trap soul',
 'abstract hip hop',
 'uk street soul',
 'teen pop',
 'latin pop',
 'salsa',
 'salsa romántica',
 'salsa choke',
 'salsa dura',
 'dembow',
 'reggaeton',
 'hi-nrg',
 'chanson française',
 'art rock',
 'easy listening',
 'electric blues',
 'field recording',
 'folk rock',
 'garage rock',
 'musical',
 'skiffle',
 'smooth jazz',
 'swing',
 'hypertechno',
 'chamber pop',
 'deep soul',
 'smooth soul',
 'indie folk',
 'acoustic rock',
 'punk',
 'rockabilly',
 'acid rock',
 'black metal',
 'doom metal',
 'stoner rock',
 'hip hop',
 'jungle',
 'italo-disco',
 'reggae-pop',
 'country rock',
 'rock opera',
 'mainstream rock',
 'techno',
 'tech house',
 'glam rock',
 'progressive pop',
 'beat music',
 'big room house',
 'electro house',
 'downtempo',
 'americana',
 'folk',
 'heartland rock',
 'boogie',
 'dub',
 'ambient',
 'deep house',
 'baroque pop',
 'piano rock',
 'chillout',
 'progressive trance',
 'vocal trance',
 'alternative country',
 'cosmic country',
 'country pop',
 'dream pop',
 'nashville sound',
 'slowcore',
 'celtic',
 'new age',
 'alternative punk',
 'britpop',
 'post-britpop',
 'art pop',
 'gangsta rap',
 'roots rock',
 'swamp rock',
 'blue-eyed soul',
 'louisiana blues',
 'classical',
 'industrial',
 'modern classical',
 'electronica',
 'instrumental',
 'plunderphonics',
 'latin',
 'bluegrass',
 'euro-trance',
 'synthwave',
 'country blues',
 'ambient trance',
 'hard trance',
 'psytrance',
 'rave',
 'tech trance',
 'outlaw country',
 'progressive country',
 'traditional country',
 'experimental',
 'glam',
 'mod',
 'psychedelic',
 'psychedelic pop',
 'psychedelic rock',
 'space rock',
 'post-punk revival',
 'trip hop',
 'pop punk',
 'punk rock',
 'pub rock',
 'nu metal',
 'neo-psychedelia',
 'big beat',
 'contemporary folk',
 'breakbeat',
 'garage house',
 'g-funk',
 'oi',
 'nu disco',
 'persian pop',
 'edm',
 'alternative hip hop',
 'conscious hip hop',
 'hardcore hip hop',
 'rap rock',
 'celtic new age',
 'glam metal',
 'pop metal',
 'gothic',
 'gothic rock',
 'progressive metal',
 'rap metal',
 'future rave',
 'hands up']

In [6]:
dados_musicas = dados_musicas[colunas_ordenadas]

PATH_ARQUIVO_DADOS_MUSICAS = PATH_DIRETORIO + 'dados_musicas.csv'
dados_musicas.to_csv(PATH_ARQUIVO_DADOS_MUSICAS, sep=';', decimal='.', index=False)

dados_musicas.tail()

,id_musica,generos,musica,media_pontos,media_pts_ganho,total_pts_calc,electro,electronic,pop,alternative metal,...,rap rock,celtic new age,glam metal,pop metal,gothic,gothic rock,progressive metal,rap metal,future rave,hands up
236,01a02706-e028-7424-9d5e-121ae4de4c60,edm|future rave|hands up|pop,My System,1506.666667,308.0,0.038,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
237,01a02706-e028-7424-9d5e-1230f5c5cc59,club|dance|dancehall|downtempo|electronic|elec...,Insomnia,1044.000000,613.0,0.422,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
238,01a02706-e028-7424-9d5e-123e77a3b087,pop|pop rock,Vindaloo,1236.000000,574.0,0.244,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
239,01a02706-e028-7424-9d5e-1246b72dec8a,folk|folk rock|indie pop|pop|pop rock|rock|sof...,My Moon My Man,1027.000000,535.0,0.011,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
240,01a02706-e028-7424-9d5e-1249c3c780cd,hip hop|pop rap|trap,Trap Queen,1364.500000,174.5,1.884,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0