# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos em um arquivo `.csv` final que 
será utilizado para programar o modelo.

In [1]:
import pandas as pd

PATH_DIRETORIO = 'dados/final/'

A seguir foram lidos os arquivos `.csv` e mesclados (_merge_) utilizando 
Pandas.

In [2]:
PATH_ARQUIVO_MUSICAS_PONTUACAO = PATH_DIRETORIO + 'kworb/transformacao/musicas_pontuacao_anual.csv'

musicas_pontuacao = pd.read_csv(PATH_ARQUIVO_MUSICAS_PONTUACAO, sep=';', decimal='.')

musicas_pontuacao.tail(3)

,id_musica,musica,media_pontos,media_pts_ganho,total_pts_calc
3928,01a02706-e02d-72a8-bbbd-06429371d930,第三个吻痕,1059.0,1059.0,0.002
3929,01a02706-e02d-72a8-bbbd-0643200f6822,Please love yourself(请好好爱自己),1194.5,303.5,0.022
3930,01a02706-e02d-72a8-bbbd-0644229abe54,Genesis HE★VENS,858.0,136.0,0.005

In [3]:
PATH_ARQUIVO_MUSICAS_GENERO_0_1 = PATH_DIRETORIO + 'musicbrainz/transformacao/musicas_generos_0_1.csv'

musicas_generos_0_1 = pd.read_csv(PATH_ARQUIVO_MUSICAS_GENERO_0_1, sep=';', decimal=',')

musicas_generos_0_1.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,emo,post-hardcore,future bass,spoken word,progressive electronic,dark wave,industrial rock,neue deutsche härte,texas blues,texas country
693,01a02706-e02c-7646-b151-786765173250,alternative rock|dream pop|indie pop|indie roc...,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
694,01a02706-e02c-7646-b151-78688c4287d2,indie pop|pop rock,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
695,01a02706-e02c-7646-b151-7892135114ed,ballad|j-pop|j-rock|pop,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dados_musicas = pd.merge(left=musicas_generos_0_1, right=musicas_pontuacao, on='id_musica')

dados_musicas.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,progressive electronic,dark wave,industrial rock,neue deutsche härte,texas blues,texas country,musica,media_pontos,media_pts_ganho,total_pts_calc
693,01a02706-e02c-7646-b151-786765173250,alternative rock|dream pop|indie pop|indie roc...,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,back to friends,2333.491228,84.473684,55.905
694,01a02706-e02c-7646-b151-78688c4287d2,indie pop|pop rock,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,undressed,1531.825000,114.700000,24.917
695,01a02706-e02c-7646-b151-7892135114ed,ballad|j-pop|j-rock|pop,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,3月9日,1484.500000,1484.500000,0.317

In [5]:


colunas = list(dados_musicas.columns)

colunas_ordenadas = colunas[:2] + colunas[-4:] + colunas[2:-4]

colunas_ordenadas

['id_musica',
 'generos',
 'musica',
 'media_pontos',
 'media_pts_ganho',
 'total_pts_calc',
 'electro',
 'electronic',
 'pop',
 'alternative metal',
 'alternative rock',
 'heavy metal',
 'pop rock',
 'post-grunge',
 'rock',
 'southern rock',
 'arena rock',
 'funk',
 'grunge',
 'hard rock',
 'house',
 'soft rock',
 'symphonic rock',
 'reggae',
 'dance',
 'dance-pop',
 'disco',
 'euro-disco',
 'europop',
 'synth-pop',
 'ballad',
 'christmas music',
 'schlager',
 'acid jazz',
 'blues',
 'blues rock',
 'classic rock',
 'metal',
 'rock and roll',
 'power metal',
 'thrash metal',
 'soul',
 'progressive rock',
 'classic country',
 'contemporary country',
 'country',
 'neo-traditional country',
 'singer-songwriter',
 'alternative r&b',
 'folk pop',
 'gospel',
 'pop soul',
 'stomp and holler',
 'alternative dance',
 'dance-rock',
 'euro house',
 'new romantic',
 'new wave',
 'post-punk',
 'sophisti-pop',
 'brill building',
 'club',
 'contemporary jazz',
 'contemporary r&b',
 'jazz',
 'jazz pop',
 'motown',
 'neo soul',
 'r&b',
 'soul jazz',
 'vocal jazz',
 'power pop',
 'afrobeat',
 'indie pop',
 'indie rock',
 'bubblegum dance',
 'bubblegum pop',
 'eurodance',
 'trance',
 'tribal house',
 'new jack swing',
 'aor',
 'dancehall',
 'festival progressive house',
 'progressive house',
 'pop rap',
 'trap',
 'k-pop',
 'alternative pop',
 'boom bap',
 'synth funk',
 'experimental hip hop',
 'jersey club rap',
 'electropop',
 'drone',
 'reductionism',
 'trap soul',
 'abstract hip hop',
 'uk street soul',
 'teen pop',
 'latin pop',
 'salsa',
 'salsa romántica',
 'salsa choke',
 'salsa dura',
 'dembow',
 'reggaeton',
 'hi-nrg',
 'chanson française',
 'art rock',
 'easy listening',
 'electric blues',
 'field recording',
 'folk rock',
 'garage rock',
 'musical',
 'skiffle',
 'smooth jazz',
 'swing',
 'hypertechno',
 'chamber pop',
 'deep soul',
 'smooth soul',
 'indie folk',
 'acoustic rock',
 'punk',
 'rockabilly',
 'acid rock',
 'black metal',
 'doom metal',
 'stoner rock',
 'hip hop',
 'jungle',
 'italo-disco',
 'reggae-pop',
 'country rock',
 'rock opera',
 'mainstream rock',
 'techno',
 'tech house',
 'glam rock',
 'progressive pop',
 'beat music',
 'big room house',
 'electro house',
 'downtempo',
 'americana',
 'folk',
 'heartland rock',
 'boogie',
 'dub',
 'ambient',
 'deep house',
 'baroque pop',
 'piano rock',
 'chillout',
 'progressive trance',
 'vocal trance',
 'alternative country',
 'cosmic country',
 'country pop',
 'dream pop',
 'nashville sound',
 'slowcore',
 'celtic',
 'new age',
 'alternative punk',
 'britpop',
 'post-britpop',
 'art pop',
 'gangsta rap',
 'roots rock',
 'swamp rock',
 'blue-eyed soul',
 'louisiana blues',
 'classical',
 'industrial',
 'modern classical',
 'electronica',
 'instrumental',
 'plunderphonics',
 'latin',
 'bluegrass',
 'euro-trance',
 'synthwave',
 'country blues',
 'ambient trance',
 'hard trance',
 'psytrance',
 'rave',
 'tech trance',
 'outlaw country',
 'progressive country',
 'traditional country',
 'experimental',
 'glam',
 'mod',
 'psychedelic',
 'psychedelic pop',
 'psychedelic rock',
 'space rock',
 'post-punk revival',
 'trip hop',
 'pop punk',
 'punk rock',
 'pub rock',
 'nu metal',
 'neo-psychedelia',
 'big beat',
 'contemporary folk',
 'breakbeat',
 'garage house',
 'g-funk',
 'oi',
 'nu disco',
 'persian pop',
 'edm',
 'alternative hip hop',
 'conscious hip hop',
 'hardcore hip hop',
 'rap rock',
 'celtic new age',
 'glam metal',
 'pop metal',
 'gothic',
 'gothic rock',
 'progressive metal',
 'rap metal',
 'future rave',
 'hands up',
 'instrumental rock',
 'garage rock revival',
 'big band',
 'indietronica',
 'horrorcore',
 'interview',
 'leftfield',
 'lo-fi',
 'non-music',
 'reggae rock',
 'turntablism',
 'uk garage',
 'free improvisation',
 'contemporary classical',
 'minimalism',
 'berlin school',
 'jersey club',
 'country folk',
 'classical crossover',
 'opera',
 'bedroom pop',
 'moombahton',
 'tropical house',
 'j-pop',
 'j-rock',
 'hyperpop',
 'surf rock',
 'funk metal',
 'rapcore',
 'electro hop',
 'fidget house',
 'electroclash',
 'alternative folk',
 'stutter house',
 'quiet storm',
 'boogie rock',
 'ambient pop',
 'cinematic classical',
 'ethereal wave',
 'post-rock',
 'shoegaze',
 'space rock revival',
 'diva house',
 'progressive breaks',
 'electro-disco',
 'industrial metal',
 'psychedelic folk',
 'funky house',
 'speed metal',
 'symphonic metal',
 'samba',
 'funk rock',
 'yacht rock',
 'ambient techno',
 'breaks',
 'jangle pop',
 'noise pop',
 'sea shanty',
 'sunshine pop',
 'doo-wop',
 'surf',
 'madchester',
 'free jazz',
 'experimental rock',
 'progressive',
 'symphonic prog',
 'bassline',
 'psychedelic soul',
 'electronic rock',
 'neo-progressive rock',
 'country soul',
 'jazz blues',
 'piano blues',
 'jazz-funk',
 'dream trance',
 'glitch pop',
 'hip house',
 'urban cowboy',
 'latin jazz',
 'christian rock',
 'contemporary christian',
 'twee pop',
 'new rave',
 'northern soul',
 'jazz rock',
 'country boogie',
 'lullaby',
 'avant-garde',
 'merseybeat',
 'lounge',
 'west coast swing',
 'baroque',
 'dubstep',
 'punk blues',
 'emo',
 'post-hardcore',
 'future bass',
 'spoken word',
 'progressive electronic',
 'dark wave',
 'industrial rock',
 'neue deutsche härte',
 'texas blues',
 'texas country']

In [6]:
dados_musicas = dados_musicas[colunas_ordenadas]

PATH_ARQUIVO_DADOS_MUSICAS = PATH_DIRETORIO + 'dados_musicas.csv'
dados_musicas.to_csv(PATH_ARQUIVO_DADOS_MUSICAS, sep=';', decimal='.', index=False)

dados_musicas.tail()

,id_musica,generos,musica,media_pontos,media_pts_ganho,total_pts_calc,electro,electronic,pop,alternative metal,...,emo,post-hardcore,future bass,spoken word,progressive electronic,dark wave,industrial rock,neue deutsche härte,texas blues,texas country
691,01a02706-e02c-7646-b151-782bfcfc1253,dance-pop|electropop|k-pop|tech house,LEMONADE,2315.892857,-18.607143,1.884,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
692,01a02706-e02c-7646-b151-78640a5906c0,pop,Homewrecker,3152.006061,9.496970,55.522,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
693,01a02706-e02c-7646-b151-786765173250,alternative rock|dream pop|indie pop|indie roc...,back to friends,2333.491228,84.473684,55.905,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
694,01a02706-e02c-7646-b151-78688c4287d2,indie pop|pop rock,undressed,1531.825000,114.700000,24.917,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
695,01a02706-e02c-7646-b151-7892135114ed,ballad|j-pop|j-rock|pop,3月9日,1484.500000,1484.500000,0.317,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0