# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos em um arquivo `.csv` final que 
será utilizado para programar o modelo.

In [1]:
import pandas as pd

PATH_DIRETORIO = 'dados/bkp/final_07/'

A seguir foram lidos os arquivos `.csv` e mesclados (_merge_) utilizando 
Pandas.

In [2]:
PATH_ARQUIVO_MUSICAS_PONTUACAO = PATH_DIRETORIO + 'kworb/transformacao/musicas_pontuacao_anual.csv'

musicas_pontuacao = pd.read_csv(PATH_ARQUIVO_MUSICAS_PONTUACAO, sep=';', decimal='.')

musicas_pontuacao.tail(3)

,id_musica,musica,media_pontos,media_pts_ganho,total_pts_calc
3928,01a02706-e02d-72a8-bbbd-06429371d930,第三个吻痕,1059.0,1059.0,0.002
3929,01a02706-e02d-72a8-bbbd-0643200f6822,Please love yourself(请好好爱自己),1194.5,303.5,0.022
3930,01a02706-e02d-72a8-bbbd-0644229abe54,Genesis HE★VENS,858.0,136.0,0.005

In [3]:
PATH_ARQUIVO_MUSICAS_GENERO_0_1 = PATH_DIRETORIO + 'musicbrainz/transformacao/musicas_generos_0_1.csv'

musicas_generos_0_1 = pd.read_csv(PATH_ARQUIVO_MUSICAS_GENERO_0_1, sep=';', decimal=',')

musicas_generos_0_1.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,new jack swing,aor,dancehall,festival progressive house,progressive house,pop rap,trap,k-pop,alternative pop,boom bap
44,01a02706-e024-7485-80f6-94cf7ab2a7a2,k-pop|pop rap|trap,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
45,01a02706-e024-7485-80f6-94d098abcb80,alternative pop|boom bap|k-pop|pop rap,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,1
46,01a02706-e024-7485-80f6-94d123beb688,k-pop|pop,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [4]:
dados_musicas = pd.merge(left=musicas_generos_0_1, right=musicas_pontuacao, on='id_musica')

dados_musicas.tail(3)

,id_musica,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,...,progressive house,pop rap,trap,k-pop,alternative pop,boom bap,musica,media_pontos,media_pts_ganho,total_pts_calc
42,01a02706-e024-7485-80f6-94986b1d0f31,dance|dancehall|dance-pop|electronic|festival ...,0,1,1,0,0,0,0,0,...,1,0,0,0,0,0,The Nights,1226.000000,400.000000,2.453
43,01a02706-e024-7485-80f6-94ce164f2db6,pop rap|trap,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,2.0,4662.035088,79.245614,11.083
44,01a02706-e024-7485-80f6-94cf7ab2a7a2,k-pop|pop rap|trap,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,Aliens,9487.500000,274.045455,2.369
45,01a02706-e024-7485-80f6-94d098abcb80,alternative pop|boom bap|k-pop|pop rap,0,0,0,0,0,0,0,0,...,0,1,0,1,1,1,Body to Body,4793.942029,122.637681,18.890
46,01a02706-e024-7485-80f6-94d123beb688,k-pop|pop,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,Butter,1006.000000,881.000000,1.877

In [13]:


colunas = list(dados_musicas.columns)

colunas_ordenadas = colunas[:2] + colunas[-4:] + colunas[2:-4]

colunas_ordenadas

['id_musica',
 'generos',
 'musica',
 'media_pontos',
 'media_pts_ganho',
 'total_pts_calc',
 'electro',
 'electronic',
 'pop',
 'alternative metal',
 'alternative rock',
 'heavy metal',
 'pop rock',
 'post-grunge',
 'rock',
 'southern rock',
 'arena rock',
 'funk',
 'grunge',
 'hard rock',
 'house',
 'soft rock',
 'symphonic rock',
 'reggae',
 'dance',
 'dance-pop',
 'disco',
 'euro-disco',
 'europop',
 'synth-pop',
 'ballad',
 'christmas music',
 'schlager',
 'acid jazz',
 'blues',
 'blues rock',
 'classic rock',
 'metal',
 'rock and roll',
 'power metal',
 'thrash metal',
 'soul',
 'progressive rock',
 'classic country',
 'contemporary country',
 'country',
 'neo-traditional country',
 'singer-songwriter',
 'alternative r&b',
 'folk pop',
 'gospel',
 'pop soul',
 'stomp and holler',
 'alternative dance',
 'dance-rock',
 'euro house',
 'new romantic',
 'new wave',
 'post-punk',
 'sophisti-pop',
 'brill building',
 'club',
 'contemporary jazz',
 'contemporary r&b',
 'jazz',
 'jazz pop',
 'motown',
 'neo soul',
 'r&b',
 'soul jazz',
 'vocal jazz',
 'power pop',
 'afrobeat',
 'indie pop',
 'indie rock',
 'bubblegum dance',
 'bubblegum pop',
 'eurodance',
 'trance',
 'tribal house',
 'new jack swing',
 'aor',
 'dancehall',
 'festival progressive house',
 'progressive house',
 'pop rap',
 'trap',
 'k-pop',
 'alternative pop',
 'boom bap']

In [15]:
dados_musicas = dados_musicas[colunas_ordenadas]

PATH_ARQUIVO_DADOS_MUSICAS = PATH_DIRETORIO + 'dados_musicas.csv'
dados_musicas.to_csv(PATH_ARQUIVO_DADOS_MUSICAS, sep=';', decimal='.')

dados_musicas.tail()

,id_musica,generos,musica,media_pontos,media_pts_ganho,total_pts_calc,electro,electronic,pop,alternative metal,...,new jack swing,aor,dancehall,festival progressive house,progressive house,pop rap,trap,k-pop,alternative pop,boom bap
42,01a02706-e024-7485-80f6-94986b1d0f31,dance|dancehall|dance-pop|electronic|festival ...,The Nights,1226.000000,400.000000,2.453,0,1,1,0,...,0,0,1,1,1,0,0,0,0,0
43,01a02706-e024-7485-80f6-94ce164f2db6,pop rap|trap,2.0,4662.035088,79.245614,11.083,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
44,01a02706-e024-7485-80f6-94cf7ab2a7a2,k-pop|pop rap|trap,Aliens,9487.500000,274.045455,2.369,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
45,01a02706-e024-7485-80f6-94d098abcb80,alternative pop|boom bap|k-pop|pop rap,Body to Body,4793.942029,122.637681,18.890,0,0,0,0,...,0,0,0,0,0,1,0,1,1,1
46,01a02706-e024-7485-80f6-94d123beb688,k-pop|pop,Butter,1006.000000,881.000000,1.877,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0