# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por acessar o banco de dados disponibilizado pela MusicBrainz[1] e salvar as informações das músicas
buscadas, essas informações são desnormalizadas e salvas em um arquivo `.csv`.

## Instalação

Para instalar foi utilizado o Podman[2] para criar uma um container Postgres[3] onde foi instalado a biblioteca Python chamada `mbslave`[4]. 

Os dados foram instalados do repositório da musicbrainz e importados para a instância postgres configurada com base no repositório[4].

Para iniciar o ambiente em container do banco de dados utilize o comando dentro da pasta `docker`:
```
podman-compose up -d
```
Caso necessário crie a pasta `data` dentro da pasta `docker` para que o volume do postgres seja armazenado nela.

Para acessar o banco de dados foi utilizado o pacote `psycopg`[5].

In [1]:
import psycopg2 

def db_connect():
    '''Conecta com o banco de dados para realizar as buscas, retorna a conexão'''
    DB_HOST = '127.0.0.1'
    DB_PORT = '5432'
    DB_DATABASE = 'musicbrainz'
    DB_USER = 'musicbrainz'
    DB_PASSWORD = 'musicbrainz'

    return psycopg2.connect(host=DB_HOST, port=DB_PORT, dbname=DB_DATABASE, user=DB_USER, password=DB_PASSWORD) 
                                # Cria a conexão com o banco de dados.       

conn = db_connect()
cursor = conn.cursor()

cursor.execute("SELECT * FROM artist a WHERE a.name = 'Rick Astley'") # Executa a consulta
artist = cursor.fetchone() # Retorna uma tupla representando uma linha da tabela

print(f"artist = {artist[2]}")

# Importante para não deixar conexões abertas no banco de dados.
cursor.close()
conn.close()

artist = Rick Astley

## Extração de dados

### Testando Busca de Gênero Musical

In [2]:
# Primeiro um teste para encontrar os genêros musicais.

artista = 'Rick Astley'
musica = 'Never Gonna Give You Up'

sql = """
    WITH genres AS (
    	SELECT 
    		g.name
    	FROM 
    		genre g
    )
    SELECT 
    	t.name
    FROM 
    	recording r 
    	INNER JOIN artist_credit ac ON ac.id = r.artist_credit 
    	INNER JOIN recording_tag rt ON rt.recording = r.id 
    	INNER JOIN tag t ON t.id = rt.tag 
    	INNER JOIN genre g ON g.name = t.name
    WHERE 
    	ac.name = %s
    	AND r.name = %s
    ORDER BY t.ref_count DESC
    LIMIT 3
"""

conn = db_connect()
cursor = conn.cursor()

cursor.execute(sql, (artista, musica))

generos = cursor.fetchall()

print(f'\nGêneros Encontrados: {[g[0] for g in generos]}')

cursor.close()
conn.close()

Gêneros Encontrados: ['rock', 'electronic', 'pop']

Exemplo Montando os `DataFrames`

In [3]:
import pandas as pd 

exemplo_df = pd.DataFrame([{'artista': artista, 'musica': musica}])

generos_str = ''
first = True
for g in generos:
    if first:
        first = False 
        generos_str = g[0]
    else :
        generos_str += '|' + g[0]

exemplo_df['generos'] = generos_str

exemplo_df

       artista                   musica              generos
0  Rick Astley  Never Gonna Give You Up  rock|electronic|pop

### Extraindo Informações para Compor novo `DataFrame`

As informações extraídas das músicas serão as tags que indicam os gêneros musica de cada música.

In [4]:


musicas_artistas = pd.read_csv('dados/final/kworb/transformacao/musicas_artistas.csv', sep=';', decimal='.')
                                # Utilizado como base para buscar as informações no banco de dados.
musicas_artistas.head()

,id_musica,musica,id_artista,artista
0,01a02706-e024-7485-80f6-934e371aaaae,For us,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
1,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
2,01a02706-e024-7485-80f6-93506f777dc5,We on Fire,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
3,01a02706-e024-7485-80f6-93516226f055,桜色Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
4,01a02706-e024-7485-80f6-935203870fca,SonoAide,01a02706-e015-716c-b555-cc88451f7ff6,-真天地開闢集団-ジグザグ

In [21]:

# PAROU EM: 
#   - Percorrer todas as musicas para fazer a buscar, verificar se utiliza multithread para realizar a consulta
# o banco é lento pois não há indíce, avaliar se a tabela inteira não vai ficar trava apesar de ser apenas operação
# de leitura. Verificar se cria multi thread, se cria indíce ou ambos. 
#   - Fazer controle para não buscar músicas repetidas em caso de erro, talvez criar novo DataFrame e escrever nele 
# quando der erro ou passar determinada quantiade de registros (analisar concorrência no caso de multithread)
for id_musica in musicas_artistas.loc[:5]['id_musica'].unique():
    musica_info = musicas_artistas[musicas_artistas['id_musica'] == id_musica]

    print('\n')
    print(id_musica)
    print(musica_info['musica'].iloc[0])
    print(musica_info['artista'].iloc[0])

01a02706-e024-7485-80f6-934e371aaaae
For us
&TEAM


01a02706-e024-7485-80f6-934f812b0450
Sakura-iro Yell
&TEAM


01a02706-e024-7485-80f6-93506f777dc5
We on Fire
&TEAM


01a02706-e024-7485-80f6-93516226f055
桜色Yell
&TEAM


01a02706-e024-7485-80f6-935203870fca
SonoAide
-真天地開闢集団-ジグザグ


01a02706-e024-7485-80f6-935302aa832a
Heart of Rainbow
.ENDRECHERI.

### Referências
[1] https://musicbrainz.org (19/08/2026)

[2] https://podman.io (19/08/2026)

[3] https://hub.docker.com/_/postgres (19/08/2026)

[4] https://github.com/acoustid/mbslave (19/08/2026)

[5] https://www.psycopg.org/docs/index.html (20/08/2026)