# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por acessar o banco de dados disponibilizado pela MusicBrainz[1] e salvar as informações das músicas
buscadas, essas informações são desnormalizadas e salvas em um arquivo `.csv`.

## Instalação

Para instalar foi utilizado o Podman[2] para criar uma um container Postgres[3] onde foi instalado a biblioteca Python chamada `mbslave`[4]. 

Os dados foram instalados do repositório da musicbrainz e importados para a instância postgres configurada com base no repositório[4].

Para iniciar o ambiente em container do banco de dados utilize o comando dentro da pasta `docker`:
```
podman-compose up -d
```
Caso necessário crie a pasta `data` dentro da pasta `docker` para que o volume do postgres seja armazenado nela.

Para acessar o banco de dados foi utilizado o pacote `psycopg`[5].

In [1]:
import psycopg2 

def db_connect():
    '''Conecta com o banco de dados para realizar as buscas, retorna a conexão'''
    DB_HOST = '127.0.0.1'
    DB_PORT = '5432'
    DB_DATABASE = 'musicbrainz'
    DB_USER = 'musicbrainz'
    DB_PASSWORD = 'musicbrainz'

    return psycopg2.connect(host=DB_HOST, port=DB_PORT, dbname=DB_DATABASE, user=DB_USER, password=DB_PASSWORD) 
                                # Cria a conexão com o banco de dados.       

conn = db_connect()
cursor = conn.cursor()

cursor.execute("SELECT * FROM artist a WHERE a.name = 'Rick Astley'") # Executa a consulta
artist = cursor.fetchone() # Retorna uma tupla representando uma linha da tabela

print(f"artist = {artist[2]}")

# Importante para não deixar conexões abertas no banco de dados.
cursor.close()
conn.close()

artist = Rick Astley

## Extração de dados

### Testando Busca de Gênero Musical

In [10]:
# Primeiro um teste para encontrar os gêneros musicais.

artista = 'Ariana Grande'
musica = 'hate that i made you love me'

sql = """
    SELECT DISTINCT
    	t.name
    FROM 
    	recording r 
    	INNER JOIN artist_credit ac ON ac.id = r.artist_credit 
    	INNER JOIN recording_tag rt ON rt.recording = r.id 
    	INNER JOIN tag t ON t.id = rt.tag 
    	INNER JOIN genre g ON g.name = t.name
    WHERE 
    	ac.name = %s
    	AND r.name = %s
"""

conn = db_connect()
cursor = conn.cursor()

cursor.execute(sql, (artista, musica))

generos = cursor.fetchall()

print(f'\nGêneros Encontrados: {[g[0] for g in generos]}')

cursor.close()
conn.close()

Gêneros Encontrados: ['pop']

Exemplo Montando os `DataFrames`

In [3]:
import pandas as pd 

exemplo_df = pd.DataFrame([{'artista': artista, 'musica': musica}])

generos_str = ''
first = True
for g in generos:
    if first:
        first = False 
        generos_str = g[0]
    else :
        generos_str += '|' + g[0]

exemplo_df['generos'] = generos_str

exemplo_df

,artista,musica,generos
0,Rick Astley,Never Gonna Give You Up,arena rock|blue-eyed soul|brutal death metal|d...

### Extraindo Informações para Compor novo `DataFrame`

Como a consulta demora serão criado indíces uma vez que o banco importado não os possui. Os indíces foram criados 
utilizando o padrão:

```
CREATE INDEX IF NOT EXISTS <nome_tabela_i_nome_coluna> ON <nome_tabela> (<coluna>);
```

Tratando se o indíce existe ou não para que não de erro ao executar as células novamente.

In [4]:
instrucoes = [ 
    "CREATE INDEX IF NOT EXISTS recording_i_id ON recording (id)",
    "CREATE INDEX IF NOT EXISTS recording_i_artist_credit ON recording (artist_credit)",
    "CREATE INDEX IF NOT EXISTS artist_credit_i_id ON artist_credit (id)",
    "CREATE INDEX IF NOT EXISTS recording_tag_i_recording ON recording_tag (recording)",
    "CREATE INDEX IF NOT EXISTS recording_tag_i_tag ON recording_tag (tag)",
    "CREATE INDEX IF NOT EXISTS tag_i_id ON tag (id)",
    "CREATE INDEX IF NOT EXISTS tag_i_name ON tag (name)",
    "CREATE INDEX IF NOT EXISTS genre_i_name ON genre (name)", 
]

conn = db_connect()
cursor = conn.cursor()

for instrucao in instrucoes:
    print(f'\nExecutando instrução \n{instrucao}')
    cursor.execute(instrucao)

cursor.close()
conn.close()

Executando instrução
CREATE INDEX IF NOT EXISTS recording_i_id ON recording (id)

Executando instrução
CREATE INDEX IF NOT EXISTS recording_i_artist_credit ON recording (artist_credit)

Executando instrução
CREATE INDEX IF NOT EXISTS artist_credit_i_id ON artist_credit (id)

Executando instrução
CREATE INDEX IF NOT EXISTS recording_tag_i_recording ON recording_tag (recording)

Executando instrução
CREATE INDEX IF NOT EXISTS recording_tag_i_tag ON recording_tag (tag)

Executando instrução
CREATE INDEX IF NOT EXISTS tag_i_id ON tag (id)

Executando instrução
CREATE INDEX IF NOT EXISTS tag_i_name ON tag (name)

Executando instrução
CREATE INDEX IF NOT EXISTS genre_i_name ON genre (name)

As informações extraídas das músicas serão as tags que indicam os gêneros musica de cada música.

In [5]:


musicas_artistas = pd.read_csv('dados/final/kworb/transformacao/musicas_artistas.csv', sep=';', decimal='.')
                                # Utilizado como base para buscar as informações no banco de dados.
musicas_artistas

,id_musica,musica,id_artista,artista
0,01a02706-e024-7485-80f6-934e371aaaae,For us,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
1,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
2,01a02706-e024-7485-80f6-93506f777dc5,We on Fire,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
3,01a02706-e024-7485-80f6-93516226f055,桜色Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
4,01a02706-e024-7485-80f6-935203870fca,SonoAide,01a02706-e015-716c-b555-cc88451f7ff6,-真天地開闢集団-ジグザグ
...,...,...,...,...
5051,01a02706-e02d-72a8-bbbd-0643200f6822,Please love yourself(请好好爱自己),01a02706-e01c-70a8-a94d-6981cf95fc3d,金色火种GoldenFire
5052,01a02706-e024-7485-80f6-948994ca0dcb,Recollect,01a02706-e01c-70a8-a94d-69821f2fb23f,鈴木このみ
5053,01a02706-e02d-72a8-bbbd-0644229abe54,Genesis HE★VENS,01a02706-e01c-70a8-a94d-6983ff400ada,鳳 瑛一(CV.緑川 光)、皇 綺羅(CV.小野大輔)、帝 ナギ(CV.代永 翼)、鳳 瑛二...
5054,01a02706-e028-7424-9d5e-11f0a30dc4e4,Voyaging Star's Farewell,01a02706-e01c-70a8-a94d-6984149a3142,鳴潮先約電台
5055,01a02706-e02d-72a8-bbbd-06429371d930,第三个吻痕,01a02706-e01c-70a8-a94d-6985fb03f6ef,黄星

In [ ]:
# Funções 
import traceback

def concatenar_lista(lista, separador=';'):
    lista_str = ''
    first = True
    for item in lista:
        if first:
            first = False 
            lista_str = item
        else :
            lista_str += separador + item
    return lista_str

def concatenar_generos(generos):
    lista = [g[0] for g in generos]

    return concatenar_lista(lista, separador='|')

PATH_ARQUIVO_MUSICA_GENEROS = "dados/musicas_generos.csv"

def escrever_linhas(linhas):
    with open(PATH_ARQUIVO_MUSICA_GENEROS, 'a') as arquivo:
        for linha in linhas:
            arquivo.write(f'{linha}\n')
            
# FIM Funções


# Inicia tratamento do arquivo que será utilizado como armazenamento dos gêneros

with open(PATH_ARQUIVO_MUSICA_GENEROS, 'a') as arquivo:
    pass # Apenas para criar o arquivo sem sobreescrever o que já existe.

arquivo_vazio = False
with open(PATH_ARQUIVO_MUSICA_GENEROS, 'r') as arquivo:
    primeira_linha = arquivo.readline().strip() # Verifica se já existe cabeçalho para o arquivo se não cria. Mas
                                                # caso exista não faz nada para poder executar a célula sem sobreescrever
                                                # o arquivo.
    
    arquivo_vazio = primeira_linha == ''


if arquivo_vazio:
    with open(PATH_ARQUIVO_MUSICA_GENEROS, 'a') as arquivo:
        arquivo.write('id_musica;generos\n') # Escreve o cabeçalho apenas se o arquivo está vazio.


sql = """
    SELECT DISTINCT
    	t.name
    FROM 
    	recording r 
    	INNER JOIN artist_credit ac ON ac.id = r.artist_credit 
    	INNER JOIN recording_tag rt ON rt.recording = r.id 
    	INNER JOIN tag t ON t.id = rt.tag 
    	INNER JOIN genre g ON g.name = t.name
    WHERE 
    	ac.name = %s
    	AND r.name = %s
"""

try: 
    conn = db_connect()
    cursor = conn.cursor()
    
    musicas_generos_df = pd.read_csv(PATH_ARQUIVO_MUSICA_GENEROS, sep=';')
    
    musicas_buscadas = musicas_generos_df['id_musica'].to_list()
    genre_rows = []
    
    print('\nIniciando busca de resultados para:')
    print('checkpoint (5)|id_musica|musica|artista')

    checkpoint = 0
    for id_musica in musicas_artistas['id_musica'].unique():
        if id_musica not in musicas_buscadas: # Condição para não buscar a mesma música me caso de musicas repetidas por 
                                                # conta do número de artistas.
    
            musica_info = musicas_artistas[musicas_artistas['id_musica'] == id_musica]

            musica = musica_info['musica'].iloc[0]
            artista = musica_info['artista'].iloc[0]
        
            print(f'\n{checkpoint}|{id_musica}|{musica}|{artista}|')
        
            cursor.execute(sql, (artista, musica))
            generos = cursor.fetchall()
        
            generos_str = concatenar_generos(generos)
            print(f'Encontrou: {generos_str}')
        
            genre_rows.append(concatenar_lista([id_musica, generos_str]))
            musicas_buscadas.append(id_musica)
            checkpoint += 1 

        if checkpoint == 5: # Salva o arquivo a cada 5 músicas buscadas
            print('\nSalvando Arquivos (checkpoint)...')
            escrever_linhas(genre_rows)
            genre_rows = []
            checkpoint = 0
            
except Exception as e:
    print('\nOcorreu um erro durante a execução')
    print(e)
    traceback.print_exc()

finally: 
    print('\nFechando conexões...')
    cursor.close()
    conn.close()

    print(f'Quantidade de músicas buscadas: {len(genre_rows)}')
    if len(genre_rows) > 0:
        print('Escrevendo gêneros encontrados...')
        escrever_linhas(genre_rows)

    print('Fim')

Iniciando busca de resultados para:
checkpoint (5)|id_musica|musica|artista

0|01a02706-e024-7485-80f6-9492e4426443|Children of Light|Atreyu|
Encontrou:

1|01a02706-e024-7485-80f6-9493a6483368|Sonic Salvation|August Burns Red|
Encontrou:

2|01a02706-e024-7485-80f6-949448360e44|On m'invite pas|Aurélie Simon|
Encontrou:

3|01a02706-e024-7485-80f6-9495a2ed8626|All Night Long|Australian Idol|
Encontrou:

4|01a02706-e024-7485-80f6-9496aefb8fc2|KiLL iT QUEEN|Ava Max|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-949717208075|Out Of Your Mind|Ava Max|
Encontrou:

1|01a02706-e024-7485-80f6-94986b1d0f31|The Nights|Avicii|
Encontrou: dance|dancehall|dance-pop|electronic|festival progressive house|house|pop|progressive house|trance

2|01a02706-e024-7485-80f6-949929ea532b|I'm With You|Avril Lavigne|
Encontrou:

3|01a02706-e024-7485-80f6-949a82065fce|Guillotine Walk|Axel Rudi Pell|
Encontrou:

4|01a02706-e024-7485-80f6-949bad4ce83c|What You Think of Me|Axel Wilder|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-949cd0f413d4|Whatever Turns You On|Axwell|
Encontrou:

1|01a02706-e024-7485-80f6-949dcb7fbcd1|Back to You|Axxima|
Encontrou:

2|01a02706-e024-7485-80f6-949e7facad40|30 STREET|Ayaka Sasaki|
Encontrou:

3|01a02706-e024-7485-80f6-949f9595e572|Heaven Baby|Ayra Starr|
Encontrou:

4|01a02706-e024-7485-80f6-94a04f2557cc|Everything's Alright|Azteck|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94a18d9095e5|Heaven Knows|B'z|
Encontrou:

1|01a02706-e024-7485-80f6-94a221079bd8|完全無欠|B'z|
Encontrou:

2|01a02706-e024-7485-80f6-94a3e1a2bb50|Mileage|B2K|
Encontrou:

3|01a02706-e024-7485-80f6-94a48dca2e94|CHOOM|BABYMONSTER|
Encontrou:

4|01a02706-e024-7485-80f6-94a53430d833|MOON|BABYMONSTER|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94a67c27146c|PSYCHO|BABYMONSTER|
Encontrou:

1|01a02706-e024-7485-80f6-94a7a554280a|SUGAR HONEY ICE TEA|BABYMONSTER|
Encontrou:

2|01a02706-e024-7485-80f6-94a857b14c25|ENERGETIC|BAND-MAID|
Encontrou:

3|01a02706-e024-7485-80f6-94a90d622bf0|BE:FIRST ALL DAY|BE:FIRST|
Encontrou:

4|01a02706-e024-7485-80f6-94aab8494856|BRUCE WAYNE|BE:FIRST|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94abde815ec9|Doesn't Really Matter|BE:FIRST|
Encontrou:

1|01a02706-e024-7485-80f6-94ac752f875f|Missing|BE:FIRST|
Encontrou:

2|01a02706-e024-7485-80f6-94ad562547c6|Muchu|BE:FIRST|
Encontrou:

3|01a02706-e024-7485-80f6-94ae664997de|Toyfriend|BE:FIRST|
Encontrou:

4|01a02706-e024-7485-80f6-94afc3419707|Why, Why|BE:FIRST|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94b060acb44f|Феникс|BEARWOLF|
Encontrou:

1|01a02706-e024-7485-80f6-94b1cc6e135c|Herz|BELA|
Encontrou:

2|01a02706-e024-7485-80f6-94b2bc4b0874|Vois sur ton chemin|BENNETT|
Encontrou:

3|01a02706-e024-7485-80f6-94b3978260b7|PENSIERO STUPENDO|BENZATO|
Encontrou:

4|01a02706-e024-7485-80f6-94b4ecc2212d|ハイテンション|BEYOOOOONDS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94b5bf691ae4|Everyday|BIALYSTOCKS|
Encontrou:

1|01a02706-e024-7485-80f6-94b6f9bf1c50|My Pace|BIBI|
Encontrou:

2|01a02706-e024-7485-80f6-94b77c4a68c2|Blau|BIBIZA|
Encontrou:

3|01a02706-e024-7485-80f6-94b8b00bf53c|NYPD|BIG KAY SMG|
Encontrou:

4|01a02706-e024-7485-80f6-94b9adb20330|Rescue Me|BIG TIM & Bell Book|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94ba9984dee7|BiiiG|BIGBANG|
Encontrou:

1|01a02706-e024-7485-80f6-94bb5dbe51b4|KILLY MANJARO|BILLA JOE|
Encontrou:

2|01a02706-e024-7485-80f6-94bc777c44bf|Unang Kilig|BINI|
Encontrou:

3|01a02706-e024-7485-80f6-94bdffa0c316|Champion|BLACKPINK|
Encontrou:

4|01a02706-e024-7485-80f6-94be9d0ebd69|Fxxxboy|BLACKPINK|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94bfb792b5f2|GO|BLACKPINK|
Encontrou:

1|01a02706-e024-7485-80f6-94c0b2964572|JUMP|BLACKPINK|
Encontrou:

2|01a02706-e024-7485-80f6-94c124f64180|Me and my|BLACKPINK|
Encontrou:

3|01a02706-e024-7485-80f6-94c20a11fb95|Anche a vent’anni si muore|BLANCO|
Encontrou:

4|01a02706-e024-7485-80f6-94c3215a5167|Ricordi|BLANCO|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94c4cbb4d50e|KUSURA BAKMA|BLOK3|
Encontrou:

1|01a02706-e024-7485-80f6-94c5bb43f7b7|You Give Me Butterflies|BLUE PONGTIWAT|
Encontrou:

2|01a02706-e024-7485-80f6-94c63b9eb8fc|BUBBLE|BMSG ALLSTARS|
Encontrou:

3|01a02706-e024-7485-80f6-94c73728436a|Standing Here|BMSG STRIKERS|
Encontrou:

4|01a02706-e024-7485-80f6-94c85fd98118|สัมผัสรัก|BOWKYLION|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94c919f48177|Boom Boom Boom|BOYNEXTDOOR|
Encontrou:

1|01a02706-e024-7485-80f6-94ca63da3ffe|VIRAL|BOYNEXTDOOR|
Encontrou:

2|01a02706-e024-7485-80f6-94cb89e5304c|ddok ddok ddok|BOYNEXTDOOR|
Encontrou:

3|01a02706-e024-7485-80f6-94ccc60d16f8|We Together|BTOB|
Encontrou:

4|01a02706-e024-7485-80f6-94cdd06521c6|2 3|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94ce164f2db6|2.0|BTS|
Encontrou: pop rap|trap

1|01a02706-e024-7485-80f6-94cf7ab2a7a2|Aliens|BTS|
Encontrou: k-pop|pop rap|trap

2|01a02706-e024-7485-80f6-94d098abcb80|Body to Body|BTS|
Encontrou: alternative pop|boom bap|k-pop|pop rap

3|01a02706-e024-7485-80f6-94d123beb688|Butter|BTS|
Encontrou: k-pop|pop

4|01a02706-e024-7485-80f6-94d25e6bb5c2|Come Over|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94d3e2d81f0c|Crystal Snow|BTS|
Encontrou:

1|01a02706-e024-7485-80f6-94d4ef40455f|Dreamers|BTS|
Encontrou:

2|01a02706-e024-7485-80f6-94d5223c710f|Dynamite|BTS|
Encontrou: dance-pop|k-pop|pop|synth funk

3|01a02706-e024-7485-80f6-94d6c6fc69cc|FYA|BTS|
Encontrou: experimental hip hop|jersey club rap|k-pop|pop rap

4|01a02706-e024-7485-80f6-94d7c12d74af|First Love|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94d8c78701ba|For You|BTS|
Encontrou:

1|01a02706-e024-7485-80f6-94d95ccac643|Hooligan|BTS|
Encontrou: k-pop|pop rap|trap

2|01a02706-e024-7485-80f6-94da877734cd|Into the Sun|BTS|
Encontrou: alternative pop|k-pop

3|01a02706-e024-7485-80f6-94db1e6dc1f6|Like Animals|BTS|
Encontrou: alternative pop|k-pop|pop rock

4|01a02706-e024-7485-80f6-94dc1a2654f2|Louder than bombs|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94dd9e7a0613|Love Maze|BTS|
Encontrou: contemporary r&b|k-pop

1|01a02706-e024-7485-80f6-94def5032daa|MIC Drop|BTS|
Encontrou:

2|01a02706-e024-7485-80f6-94dfc1501091|Magic Shop|BTS|
Encontrou: contemporary r&b|electropop|k-pop

3|01a02706-e024-7485-80f6-94e073753ee1|Merry Go Round|BTS|
Encontrou: contemporary r&b|k-pop|synth-pop

4|01a02706-e024-7485-80f6-94e180284ed4|Mikrokosmos|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94e2965f8e3f|NORMAL|BTS|
Encontrou: alternative pop|contemporary r&b|k-pop

1|01a02706-e024-7485-80f6-94e311b64844|No. 29|BTS|
Encontrou: drone|reductionism

2|01a02706-e024-7485-80f6-94e4da6cfbe9|One More Night|BTS|
Encontrou: dance-pop|k-pop

3|01a02706-e024-7485-80f6-94e5c2b5eacd|Pied Piper|BTS|
Encontrou:

4|01a02706-e024-7485-80f6-94e6cbdd4b1f|Please|BTS|
Encontrou: k-pop|trap soul

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94e77dbef5ec|Run|BTS|
Encontrou:

1|01a02706-e024-7485-80f6-94e8a96095cb|Run BTS|BTS|
Encontrou:

2|01a02706-e024-7485-80f6-94e93ad91f66|SWIM|BTS|
Encontrou: abstract hip hop|alternative pop|k-pop|uk street soul

3|01a02706-e024-7485-80f6-94ea91a46c8b|SWIM with Jimin|BTS|
Encontrou:

4|01a02706-e024-7485-80f6-94ebfe167660|SWIM with Jin|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94ec846a2a1d|SWIM with Jung Kook|BTS|
Encontrou:

1|01a02706-e024-7485-80f6-94ed9f3ff75d|SWIM with RM|BTS|
Encontrou:

2|01a02706-e024-7485-80f6-94eec0218f4c|SWIM with SUGA|BTS|
Encontrou:

3|01a02706-e024-7485-80f6-94ef3ae2ffcc|SWIM with V|BTS|
Encontrou:

4|01a02706-e024-7485-80f6-94f0b95370b7|SWIM with j-hope|BTS|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94f12b86942e|they don’t know ’bout us|BTS|
Encontrou: k-pop|pop rap|trap soul

1|01a02706-e024-7485-80f6-94f27dbc9a68|Opalite|BUNT.|
Encontrou:

2|01a02706-e024-7485-80f6-94f3b3307881|TRIPPIN|BUNT.|
Encontrou:

3|01a02706-e024-7485-80f6-94f45ad92bf2|BLACK WATER DAMNED|BURNIN' BRIDGES Ai Music|
Encontrou:

4|01a02706-e024-7485-80f6-94f5b5dc4f0d|ROCKET|BURNOUT SYNDROMES|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94f63bbd788c|คับเฮีย|BUS|
Encontrou:

1|01a02706-e024-7485-80f6-94f799ec0de6|Title Track|Babu Singh Maan - Dhurandhar|
Encontrou:

2|01a02706-e024-7485-80f6-94f878152dc5|Tucamacarena|Baby K|
Encontrou:

3|01a02706-e024-7485-80f6-94f98b521034|Yes Sir, I Can Boogie|Baccara|
Encontrou: disco|electronic|europop|pop

4|01a02706-e024-7485-80f6-94fa350473c1|Buses And Trains|Bachelor Girl|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-94fbb3b68e3d|Bottle Up|Backstreet Boys|
Encontrou:

1|01a02706-e024-7485-80f6-94fc1e14ef61|I Want It That Way|Backstreet Boys|
Encontrou: ballad|bubblegum pop|contemporary r&b|dance|dance-pop|electropop|europop|funk|pop|soul|teen pop

2|01a02706-e024-7485-80f6-94fde674bb83|Shape of My Heart|Backstreet Boys|
Encontrou: dance-pop|pop|teen pop

3|01a02706-e024-7485-80f6-94fea6ae481d|BAILE INoLVIDABLE|Bad Bunny|
Encontrou: latin pop|pop|salsa|salsa romántica

4|01a02706-e024-7485-80f6-94ff08b012db|CAFé CON RON|Bad Bunny|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-95003e175995|DtMF|Bad Bunny|
Encontrou: latin pop|pop

1|01a02706-e024-7485-80f6-95011579a47d|DÁKITI|Bad Bunny|
Encontrou:

2|01a02706-e024-7485-80f6-9502feb59631|El Apagón|Bad Bunny|
Encontrou:

3|01a02706-e024-7485-80f6-950381d19577|EoO|Bad Bunny|
Encontrou:

4|01a02706-e024-7485-80f6-9504799f4f6c|I Like It|Bad Bunny|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e024-7485-80f6-950524b4a0e4|LA CANCIÓN|Bad Bunny|
Encontrou:

1|01a02706-e024-7485-80f6-950625515ca6|LA MuDANZA|Bad Bunny|
Encontrou: salsa|salsa choke|salsa dura

2|01a02706-e024-7485-80f6-950738ab3897|LO QUE LE PASÓ A HAWAii|Bad Bunny|
Encontrou:

3|01a02706-e024-7485-80f6-950895fb220f|MIA|Bad Bunny|
Encontrou:

4|01a02706-e025-732e-b5ae-1258a4321ec0|MONACO|Bad Bunny|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-1259de4b0563|Me Porto Bonito|Bad Bunny|
Encontrou:

1|01a02706-e025-732e-b5ae-125a4e156c23|NUEVAYoL|Bad Bunny|
Encontrou: dembow|latin pop|pop

2|01a02706-e025-732e-b5ae-125bbb5232c7|Safaera|Bad Bunny|
Encontrou:

3|01a02706-e025-732e-b5ae-125c41e5f808|Tití Me Preguntó|Bad Bunny|
Encontrou:

4|01a02706-e025-732e-b5ae-125dbd07174c|VOY A LLeVARTE PA PR|Bad Bunny|
Encontrou: latin pop|reggaeton

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-125e9fa263a8|Yo Perreo Sola|Bad Bunny|
Encontrou:

1|01a02706-e025-732e-b5ae-125f6c1ee06c|Silver Night|Bad Style|
Encontrou:

2|01a02706-e025-732e-b5ae-12601550979c|Just Believe|Bailey Zimmerman|
Encontrou:

3|01a02706-e025-732e-b5ae-1261afff5ac1|Please Don't Move To Melbourne|Ball Park Music|
Encontrou:

4|01a02706-e025-732e-b5ae-1262680e7fac|Stranger Things|Baltic House Orchestra|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-12631c8191c0|Resta Con Me|Bambole Di Pezza|
Encontrou:

1|01a02706-e025-732e-b5ae-1264ffe37a8b|Venus|Bananarama|
Encontrou: dance-pop|dance-rock|disco|electronic|europop|hi-nrg|house|new wave|pop|pop rock|rock|synth-pop

2|01a02706-e025-732e-b5ae-1265bf695ae8|Uitslover|Bankzitters|
Encontrou:

3|01a02706-e025-732e-b5ae-1266e8600b84|Voilà|Barbara Pravi|
Encontrou: chanson française

4|01a02706-e025-732e-b5ae-1267b4aa7dcc|Get Your Sparkle On|Barbie|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-126890dbc4ee|The Way We Were|Barbra Streisand|
Encontrou: alternative rock|art rock|ballad|blues rock|classic rock|contemporary jazz|easy listening|electric blues|field recording|folk rock|garage rock|hard rock|indie rock|jazz|musical|pop|pop rock|skiffle|smooth jazz|soft rock|soul jazz|swing

1|01a02706-e025-732e-b5ae-126916720759|Feel Alive|Bastille|
Encontrou:

2|01a02706-e025-732e-b5ae-126ab3bd79a5|Magnetic|Bausa|
Encontrou: dance|dance-pop|electronic

3|01a02706-e025-732e-b5ae-126bd0b2ecac|Wolke 4|Bausa|
Encontrou:

4|01a02706-e025-732e-b5ae-126ca179954f|Bullshit|Beartooth|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-126d4a16b477|Eyes Closed|Beartooth|
Encontrou:

1|01a02706-e025-732e-b5ae-126eda310641|Alles hat seine Zeit|BearyTunes|
Encontrou:

2|01a02706-e025-732e-b5ae-126f79fa98fc|Dankbar|BearyTunes|
Encontrou:

3|01a02706-e025-732e-b5ae-1270e03bdb30|Die Liebe bleibt|BearyTunes|
Encontrou:

4|01a02706-e025-732e-b5ae-12715e9501e5|Glaub an dich|BearyTunes|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-1272c59c9993|Gute Reise, mein Freund|BearyTunes|
Encontrou:

1|01a02706-e025-732e-b5ae-1273649a319a|Ich bin genug|BearyTunes|
Encontrou:

2|01a02706-e025-732e-b5ae-12743a2e695b|Liebe ist das Mutigste auf dieser Welt|BearyTunes|
Encontrou:

3|01a02706-e025-732e-b5ae-1275a6ffd2a6|Mut|BearyTunes|
Encontrou:

4|01a02706-e025-732e-b5ae-12762d735ae2|Nicht im Wunderland|BearyTunes|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-127777c2d84a|Unser sicherer Hafen|BearyTunes|
Encontrou:

1|01a02706-e025-732e-b5ae-127885935d1e|Was kommt, das kommt|BearyTunes|
Encontrou:

2|01a02706-e025-732e-b5ae-1279becb6d31|Alibi|Beatrice Egli|
Encontrou:

3|01a02706-e025-732e-b5ae-127a35c1b7ec|So schön cha s'Läbe si|Beatrice Egli|
Encontrou:

4|01a02706-e025-732e-b5ae-127b97d8b5d9|Hysteria|Bebe Rexha|
Encontrou: dance-pop|electropop|hypertechno

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-127c4d7268ff|New Religion|Bebe Rexha|
Encontrou:

1|01a02706-e025-732e-b5ae-127da8b75b4c|Sad Girls|Bebe Rexha|
Encontrou:

2|01a02706-e025-732e-b5ae-127ead284c84|Disappearing Act|Beck|
Encontrou:

3|01a02706-e025-732e-b5ae-127fcc9cc3bf|Ride Lonesome|Beck|
Encontrou:

4|01a02706-e025-732e-b5ae-12803741b137|Make It Count|Becky G|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-12814eec9af2|Shower|Becky G|
Encontrou: alternative dance|chamber pop|contemporary r&b|electropop|pop|pop rap|teen pop

1|01a02706-e025-732e-b5ae-128219a7645f|Sorry Papi|Becky G|
Encontrou:

2|01a02706-e025-732e-b5ae-1283eba86af1|Te Olvido|Becky G|
Encontrou:

3|01a02706-e025-732e-b5ae-128457be0a53|More More More|Becky Hill|
Encontrou:

4|01a02706-e025-732e-b5ae-1285e7a58727|รักฉันบ้างหรือเปล่า|Becky Rebecca|
Encontrou:

Salvando Arquivos (checkpoint)...

0|01a02706-e025-732e-b5ae-1286e05be73b|แค่มีเธอก็พอแล้ว|Becky Rebecca|
Encontrou:

1|01a02706-e025-732e-b5ae-128755ef80bf|Meteo-Right|Believe (CV: Misaki Akiyama)|
Encontrou:

2|01a02706-e025-732e-b5ae-1288caca55b1|iloveitiloveitiloveit|Bella Kay|

### Referências
[1] https://musicbrainz.org (19/08/2026)

[2] https://podman.io (19/08/2026)

[3] https://hub.docker.com/_/postgres (19/08/2026)

[4] https://github.com/acoustid/mbslave (19/08/2026)

[5] https://www.psycopg.org/docs/index.html (20/08/2026)