# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos de `extrair_dados_musicrainz_pratica`.

Utiliando arquivo extraído vamos montar o arquivo que reuni os a música, gênero e pontuações para ser utilizado no
treinamento do modelo.

Músicas sem gênero não foram consideradas, apesar de remover os dados não ser uma boa prática o ideal seria utilizar um modelo que populasse os gêneros de acordo com outras caracterstícas, 
mas isso pode ser uma outra atividade por tanto foi utilizado apenas as músicas com genêro para realizar o teste do modelo.

In [1]:
import pandas as pd

PATH_DIRETORIO = 'dados/bkp/final_07/musicbrainz/'

PATH_ARQUIVO_MUSICAS_GENEROS = PATH_DIRETORIO + 'musicas_generos.csv'

musicas_generos_df = pd.read_csv(PATH_ARQUIVO_MUSICAS_GENEROS, sep=';', decimal=',')

musicas_generos_df = musicas_generos_df.dropna().reset_index()[['id_musica', 'generos']].set_index('id_musica')

musicas_generos_df.tail(10)

                                                                                generos
id_musica
01a02706-e024-7485-80f6-9471c1a7f490                                                pop
01a02706-e024-7485-80f6-947637e23f0d                                                pop
01a02706-e024-7485-80f6-9479a46ef6de                              ballad|new jack swing
01a02706-e024-7485-80f6-947c577b5ad5                                     new jack swing
01a02706-e024-7485-80f6-948bdb006b36  aor|arena rock|classic rock|pop|pop rock|progr...
01a02706-e024-7485-80f6-94986b1d0f31  dance|dancehall|dance-pop|electronic|festival ...
01a02706-e024-7485-80f6-94ce164f2db6                                       pop rap|trap
01a02706-e024-7485-80f6-94cf7ab2a7a2                                 k-pop|pop rap|trap
01a02706-e024-7485-80f6-94d098abcb80             alternative pop|boom bap|k-pop|pop rap
01a02706-e024-7485-80f6-94d123beb688                                          k-pop|pop

Os genêros são separados por `|` foram criados colunas nos `DataFrames`
para cada gênero encontrado, dessa maneira a coluna irá possuir o valor de `0` indicando que 
não pertence a aquele gênero e `1` indicando que pertence.

In [2]:
# 'id_musica' in musicas_generos_df.columns.values

with open(PATH_ARQUIVO_MUSICAS_GENEROS, 'r') as arquivo:
    first = True
    for linha in arquivo:
        if first : # Pula a primeira linha que é o cabeçalho
            first = False
            continue 
        
        id_musica, generos_str = linha.strip().split(';')

        generos = [] # Transforma os gêneros em lista para serem percorridos
        if generos_str != '':
            generos = generos_str.strip().split('|')

        #print(f'id_musica:{id_musica} , generos:{generos}')

        for genero in generos:

            if genero not in musicas_generos_df.columns.values: # Inicializa a coluna caso
                                                                # ainda não exista
                musicas_generos_df[genero] = 0

            musicas_generos_df.loc[id_musica, genero] = 1 # Atribui 1 nas colunas em que 
                                                            # a música pertence ao gênero.

musicas_generos_df.tail(3)

,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,rock,...,new jack swing,aor,dancehall,festival progressive house,progressive house,pop rap,trap,k-pop,alternative pop,boom bap
id_musica,,,,,,,,,,,,,,,,,,,,,
01a02706-e024-7485-80f6-94cf7ab2a7a2,k-pop|pop rap|trap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
01a02706-e024-7485-80f6-94d098abcb80,alternative pop|boom bap|k-pop|pop rap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,1
01a02706-e024-7485-80f6-94d123beb688,k-pop|pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [3]:
PATH_ARQUIVO_MUSICA_GENEROS_0_1 = PATH_DIRETORIO + 'musicas_generos_0_1.csv'

musicas_generos_df.to_csv(PATH_ARQUIVO_MUSICA_GENEROS_0_1, sep=';', decimal=',')

musicas_generos_df

,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,rock,...,new jack swing,aor,dancehall,festival progressive house,progressive house,pop rap,trap,k-pop,alternative pop,boom bap
id_musica,,,,,,,,,,,,,,,,,,,,,
01a02706-e024-7485-80f6-935a3c2770ff,electro|electronic|pop,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935c776327ac,alternative metal|alternative rock|heavy metal...,0,0,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935d5d4a5e5e,alternative metal|alternative rock|arena rock|...,0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935e17059cc1,alternative rock|rock,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935fd9c527ce,alternative metal|alternative rock|arena rock|...,0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9360b7fefe5a,alternative rock|hard rock|pop|pop rock|post-g...,0,0,1,0,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93610290ee65,alternative metal|alternative rock|hard rock|h...,0,0,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-936284400805,alternative rock|pop|rock,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93755cd0da4c,dance|dance-pop|disco|electronic|euro-disco|eu...,0,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-937662d33384,dance|dance-pop|disco|electronic|euro-disco|eu...,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9378c69f5586,ballad|christmas music|dance-pop|disco|europop...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9379c9b8b6e0,acid jazz|ballad|dance|dance-pop|disco|euro-di...,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-937a74494885,hard rock,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-937b0e1f6c82,arena rock|blues|blues rock|classic rock|hard ...,0,0,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93b9787d3276,hard rock|heavy metal|metal|power metal|rock|t...,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93badcc56203,hard rock|heavy metal|metal|power metal|rock,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93c6b8b97436,soul,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93d3efcfc089,arena rock|blues|blues rock|classic rock|hard ...,0,0,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93f04860a37d,classic country|contemporary country|country|n...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93f42ac8dc9c,alternative rock|pop|pop rock|rock|singer-song...,0,0,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-93fbce2167d1,alternative r&b|pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9401ce722749,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-940201e7789e,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-94039db25a4e,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-940543d486f2,ballad|folk pop|gospel|pop|pop rock|pop soul|s...,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9411b81c3887,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-941babf1efea,alternative dance|alternative rock|ballad|danc...,0,1,1,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-941c76870791,alternative metal|rock,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-942873996ad9,blues|brill building|club|contemporary jazz|co...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-942a9a4ff55e,power pop,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-94345a3b65b3,europop|pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-944201ea0a32,afrobeat|electronic,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-944a75046939,club|dance|disco|funk|pop|r&b|rock|soul,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-94541444d258,indie pop|indie rock|pop|rock,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-945be175dd02,dance-pop,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9467698ac356,bubblegum dance|bubblegum pop|club|dance|dance...,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-946bc14d9ce6,electronic|new romantic|new wave|pop|rock|synt...,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9471c1a7f490,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-947637e23f0d,pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-9479a46ef6de,ballad|new jack swing,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-947c577b5ad5,new jack swing,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-948bdb006b36,aor|arena rock|classic rock|pop|pop rock|progr...,0,0,1,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-94986b1d0f31,dance|dancehall|dance-pop|electronic|festival ...,0,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
01a02706-e024-7485-80f6-94ce164f2db6,pop rap|trap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
01a02706-e024-7485-80f6-94cf7ab2a7a2,k-pop|pop rap|trap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
01a02706-e024-7485-80f6-94d098abcb80,alternative pop|boom bap|k-pop|pop rap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,1
01a02706-e024-7485-80f6-94d123beb688,k-pop|pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0