# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos de `extrair_dados_kworb_pratica`.

## Tratando a estrutura do ranque de músicas extraído

In [1]:
import pandas as pd

ww_2026_df = pd.read_csv('dados/final/kworb/kworb_ww_2026.csv', sep=';', decimal='.')

ww_2026_df.head()

        artista               musica  pontos  pts_ganho  pts_calc      data
0           BTS              Run BTS   21817      21487     0.585  20260101
1  Taylor Swift  The Fate of Ophelia   18402       -955     1.595  20260101
2       HUNTR/X               Golden   18113        -73     3.038  20260101
3          EJAE               Golden   18113        -73     3.038  20260101
4   AUDREY NUNA               Golden   18113        -73     3.038  20260101

Nota-se que há registros repetidos, isso se dá pelo motivo de um artista participar da mesma música, mas a música ser diferente na tabela kworb por conta da participação dos artistas, para isso será considerado que o artista e a música são a mesma uma vez que ele está em ambas.

In [2]:
ww_2026_df[ww_2026_df['musica'] == 'Usagi Rap'].head()

,artista,musica,pontos,pts_ganho,pts_calc,data
44161,Usagi(CV:Ozawa Ari),Usagi Rap,1341,1341,0.001,20260725
44162,Mermaid(CV:Oki Saeko),Usagi Rap,1341,1341,0.001,20260725
44163,Mermaid(CV:Nanase Ayaka),Usagi Rap,1341,1341,0.001,20260725
44189,Usagi(CV:Ozawa Ari),Usagi Rap,1193,1193,0.001,20260725
44190,Momonga(CV:Iguchi Yuka),Usagi Rap,1193,1193,0.001,20260725

In [3]:
usagi_rap = ww_2026_df[ww_2026_df['musica'] == 'Usagi Rap']
usagi_rap.iloc[0:5].groupby(by='musica')['pontos'].sum()

musica
Usagi Rap    6409
Name: pontos, dtype: int64

In [4]:
usagi_rap.iloc[0:5]

,artista,musica,pontos,pts_ganho,pts_calc,data
44161,Usagi(CV:Ozawa Ari),Usagi Rap,1341,1341,0.001,20260725
44162,Mermaid(CV:Oki Saeko),Usagi Rap,1341,1341,0.001,20260725
44163,Mermaid(CV:Nanase Ayaka),Usagi Rap,1341,1341,0.001,20260725
44189,Usagi(CV:Ozawa Ari),Usagi Rap,1193,1193,0.001,20260725
44190,Momonga(CV:Iguchi Yuka),Usagi Rap,1193,1193,0.001,20260725

Exemplos dos registros repetidos acontecem pois há músicas com quatro artistas onde dos quatro, três artistas se repetem, as linhas no kworb são as seguintes:

Usagi(CV:Ozawa Ari), Momonga(CV:Iguchi Yuka), Mermaid(CV:Oki Saeko) & Mermaid(CV:Nanase Ayaka) - Usagi Rap

Usagi(CV:Ozawa Ari), Mermaid(CV:Oki Saeko) & Mermaid(CV:Nanase Ayaka) - Usagi Rap

In [5]:
repetidos = ww_2026_df[ww_2026_df['musica'] == 'Usagi Rap']

repetidos.head(20) # Há registros repetidos pois há músicas com 4 artistas onde o três artistas

,artista,musica,pontos,pts_ganho,pts_calc,data
44161,Usagi(CV:Ozawa Ari),Usagi Rap,1341,1341,0.001,20260725
44162,Mermaid(CV:Oki Saeko),Usagi Rap,1341,1341,0.001,20260725
44163,Mermaid(CV:Nanase Ayaka),Usagi Rap,1341,1341,0.001,20260725
44189,Usagi(CV:Ozawa Ari),Usagi Rap,1193,1193,0.001,20260725
44190,Momonga(CV:Iguchi Yuka),Usagi Rap,1193,1193,0.001,20260725
44191,Mermaid(CV:Oki Saeko),Usagi Rap,1193,1193,0.001,20260725
44192,Mermaid(CV:Nanase Ayaka),Usagi Rap,1193,1193,0.001,20260725
44406,Usagi(CV:Ozawa Ari),Usagi Rap,1479,138,0.003,20260726
44407,Mermaid(CV:Oki Saeko),Usagi Rap,1479,138,0.003,20260726
44408,Mermaid(CV:Nanase Ayaka),Usagi Rap,1479,138,0.003,20260726
44429,Usagi(CV:Ozawa Ari),Usagi Rap,1341,148,0.003,20260726
44430,Momonga(CV:Iguchi Yuka),Usagi Rap,1341,148,0.003,20260726
44431,Mermaid(CV:Oki Saeko),Usagi Rap,1341,148,0.003,20260726
44432,Mermaid(CV:Nanase Ayaka),Usagi Rap,1341,148,0.003,20260726
44669,Usagi(CV:Ozawa Ari),Usagi Rap,1450,-29,0.004,20260727
44670,Mermaid(CV:Oki Saeko),Usagi Rap,1450,-29,0.004,20260727
44671,Mermaid(CV:Nanase Ayaka),Usagi Rap,1450,-29,0.004,20260727
44682,Usagi(CV:Ozawa Ari),Usagi Rap,1368,27,0.004,20260727
44683,Momonga(CV:Iguchi Yuka),Usagi Rap,1368,27,0.004,20260727
44684,Mermaid(CV:Oki Saeko),Usagi Rap,1368,27,0.004,20260727

In [6]:
grupo_repetidos = repetidos.groupby(by=['artista', 'musica', 'data']).sum()
grupo_repetidos

                                             pontos  pts_ganho  pts_calc
artista                  musica    data
Mermaid(CV:Nanase Ayaka) Usagi Rap 20260725    2534       2534     0.002
                                   20260726    2820        286     0.006
                                   20260727    2818         -2     0.008
                                   20260728    2906         88     0.011
                                   20260729    2903         -3     0.014
...                                             ...        ...       ...
Usagi(CV:Ozawa Ari)      Usagi Rap 20260815    2187        -24     0.053
                                   20260816    2318        131     0.056
                                   20260817    2229        -89     0.058
                                   20260818    2103       -126     0.060
                                   20260820    1041        114     0.031

[101 rows x 3 columns]

Note que dessa maneira não há mais músicas repetidas para o artista, se um artista participa da mesma música em mais de uma vez é contando como uma música só.

In [7]:
grupo_repetidos.xs('Usagi(CV:Ozawa Ari)', level='artista')

                    pontos  pts_ganho  pts_calc
musica    data
Usagi Rap 20260725    2534       2534     0.002
          20260726    2820        286     0.006
          20260727    2818         -2     0.008
          20260728    2906         88     0.011
          20260729    2903         -3     0.014
          20260730    2740       -163     0.017
          20260731    2390       -350     0.019
          20260801    2276       -114     0.021
          20260802    2300         24     0.023
          20260803    2472        172     0.026
          20260804    2300       -172     0.028
          20260805    1125        -92     0.016
          20260806    1104        -21     0.017
          20260807    1104          0     0.018
          20260808    2273        294     0.037
          20260809    2318         45     0.040
          20260810    2276        -42     0.042
          20260811    2341         65     0.044
          20260812    2363         22     0.046
          20260813    2363          0     0.048
          20260814    2211       -152     0.050
          20260815    2187        -24     0.053
          20260816    2318        131     0.056
          20260817    2229        -89     0.058
          20260818    2103       -126     0.060
          20260820    1041        114     0.031

Agora será feito o tratamento para todo o `DataFrame`.

In [8]:
ww_2026_df_group = ww_2026_df.groupby(by=['artista', 'musica', 'data']).sum()

ww_2026_df = ww_2026_df_group.reset_index() # Reset index faz com o que o `DataFrame` tenha o índice reiniciado 
                                            # para poder operar como `DataFrame`[1].
ww_2026_df.head(10)

         artista           musica      data  pontos  pts_ganho  pts_calc
0          &TEAM           For us  20260801    2389       2389     0.002
1          &TEAM           For us  20260802    1765       -624     0.004
2          &TEAM  Sakura-iro Yell  20260314    1265       1265     0.001
3          &TEAM  Sakura-iro Yell  20260406    1083       1083     0.004
4          &TEAM  Sakura-iro Yell  20260407    1151         68     0.005
5          &TEAM       We on Fire  20260413    1435       1435     0.001
6          &TEAM       We on Fire  20260414    1050       -385     0.002
7          &TEAM           桜色Yell  20260314    1177       1177     0.001
8  -真天地開闢集団-ジグザグ         SonoAide  20260603    1538       1538     0.002
9  -真天地開闢集団-ジグザグ         SonoAide  20260604    1341       -197     0.003

## Separando os Artistas das Músicas mantendo o vínculo

### Criando novos `DataFrames` para vínculo

In [9]:
import uuid

artistas = pd.DataFrame(ww_2026_df['artista'].unique(), columns=['artista']) # Criado para operacoes relacionadas a 
                                                                                # artista

artistas['id_artista'] = artistas['artista'].apply(lambda _: uuid.uuid7())

artistas.head(10)

         artista                            id_artista
0          &TEAM  01a02706-e015-716c-b555-cc87bebd5c11
1  -真天地開闢集団-ジグザグ  01a02706-e015-716c-b555-cc88451f7ff6
2   .ENDRECHERI.  01a02706-e015-716c-b555-cc897fc5c965
3        10-FEET  01a02706-e015-716c-b555-cc8a55f0b28c
4           1119  01a02706-e015-716c-b555-cc8b9f0a0417
5        1986zig  01a02706-e015-716c-b555-cc8ce042ab8e
6   20th Century  01a02706-e015-716c-b555-cc8de33e2c5c
7    2facecapone  01a02706-e015-716c-b555-cc8e0e4a2a0e
8   2raumwohnung  01a02706-e015-716c-b555-cc8f88b9f61f
9   3 Doors Down  01a02706-e015-716c-b555-cc90157d7a43

In [10]:
musicas = pd.DataFrame(ww_2026_df['musica'].unique(), columns=['musica']) # Fazer o mesmo para as músicas

musicas['id_musica'] = musicas['musica'].apply(lambda _: uuid.uuid7())

musicas.head(10)

                musica                             id_musica
0               For us  01a02706-e024-7485-80f6-934e371aaaae
1      Sakura-iro Yell  01a02706-e024-7485-80f6-934f812b0450
2           We on Fire  01a02706-e024-7485-80f6-93506f777dc5
3               桜色Yell  01a02706-e024-7485-80f6-93516226f055
4             SonoAide  01a02706-e024-7485-80f6-935203870fca
5     Heart of Rainbow  01a02706-e024-7485-80f6-935302aa832a
6        Thinking Time  01a02706-e024-7485-80f6-9354df9d2b15
7  Burn Out to Nothing  01a02706-e024-7485-80f6-9355e1b89719
8                福气马上来  01a02706-e024-7485-80f6-9356a7fa1502
9      Nur dir gehör'n  01a02706-e024-7485-80f6-935702e3fc99

In [11]:
ww_2026 = pd.merge(left=ww_2026_df, right=artistas, on='artista')

ww_2026 = pd.merge(left=ww_2026, right=musicas, on='musica')

ww_2026

,artista,musica,data,pontos,pts_ganho,pts_calc,id_artista,id_musica
0,&TEAM,For us,20260801,2389,2389,0.002,01a02706-e015-716c-b555-cc87bebd5c11,01a02706-e024-7485-80f6-934e371aaaae
1,&TEAM,For us,20260802,1765,-624,0.004,01a02706-e015-716c-b555-cc87bebd5c11,01a02706-e024-7485-80f6-934e371aaaae
2,&TEAM,Sakura-iro Yell,20260314,1265,1265,0.001,01a02706-e015-716c-b555-cc87bebd5c11,01a02706-e024-7485-80f6-934f812b0450
3,&TEAM,Sakura-iro Yell,20260406,1083,1083,0.004,01a02706-e015-716c-b555-cc87bebd5c11,01a02706-e024-7485-80f6-934f812b0450
4,&TEAM,Sakura-iro Yell,20260407,1151,68,0.005,01a02706-e015-716c-b555-cc87bebd5c11,01a02706-e024-7485-80f6-934f812b0450
...,...,...,...,...,...,...,...,...
50144,鈴木このみ,Recollect,20260424,1184,1184,0.004,01a02706-e01c-70a8-a94d-69821f2fb23f,01a02706-e024-7485-80f6-948994ca0dcb
50145,鈴木このみ,Recollect,20260425,1077,-107,0.006,01a02706-e01c-70a8-a94d-69821f2fb23f,01a02706-e024-7485-80f6-948994ca0dcb
50146,鳳 瑛一(CV.緑川 光)、皇 綺羅(CV.小野大輔)、帝 ナギ(CV.代永 翼)、鳳 瑛二...,Genesis HE★VENS,20260321,858,136,0.005,01a02706-e01c-70a8-a94d-6983ff400ada,01a02706-e02d-72a8-bbbd-0644229abe54
50147,鳴潮先約電台,Voyaging Star's Farewell,20260209,1488,559,0.002,01a02706-e01c-70a8-a94d-6984149a3142,01a02706-e028-7424-9d5e-11f0a30dc4e4
50148,黄星,第三个吻痕,20260401,1059,1059,0.001,01a02706-e01c-70a8-a94d-6985fb03f6ef,01a02706-e02d-72a8-bbbd-06429371d930

Para existir um vínculo entre artistas e e músicas foram selecionados as colunas do `DataFrame` com ambas as informações
e em seguida utilizado o método `drop_duplicates` do Pandas[2]. O índice foi reinicado apenas para recriá-lo.

### Salvando vínculo entre artistas e músicas

Salvando o vínculo

In [12]:
musicas_artistas_df = ww_2026[['id_musica', 'musica', 'id_artista', 'artista']].drop_duplicates().reset_index()[['id_musica', 'musica', 'id_artista', 'artista']]

musicas_artistas_df.to_csv('dados/musicas_artistas.csv', sep=';', decimal='.', index=False) # Salvando o vínculo.

musicas_artistas_df.head()

,id_musica,musica,id_artista,artista
0,01a02706-e024-7485-80f6-934e371aaaae,For us,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
1,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
2,01a02706-e024-7485-80f6-93506f777dc5,We on Fire,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
3,01a02706-e024-7485-80f6-93516226f055,桜色Yell,01a02706-e015-716c-b555-cc87bebd5c11,&TEAM
4,01a02706-e024-7485-80f6-935203870fca,SonoAide,01a02706-e015-716c-b555-cc88451f7ff6,-真天地開闢集団-ジグザグ

In [13]:
artistas.to_csv('dados/artistas.csv', sep=';', decimal='.', index=False) # Salvando artistas.

artistas.head()

         artista                            id_artista
0          &TEAM  01a02706-e015-716c-b555-cc87bebd5c11
1  -真天地開闢集団-ジグザグ  01a02706-e015-716c-b555-cc88451f7ff6
2   .ENDRECHERI.  01a02706-e015-716c-b555-cc897fc5c965
3        10-FEET  01a02706-e015-716c-b555-cc8a55f0b28c
4           1119  01a02706-e015-716c-b555-cc8b9f0a0417

In [14]:
musicas.to_csv('dados/musicas.csv', sep=';', decimal='.', index=False) # Salvando artistas.

musicas.head()

            musica                             id_musica
0           For us  01a02706-e024-7485-80f6-934e371aaaae
1  Sakura-iro Yell  01a02706-e024-7485-80f6-934f812b0450
2       We on Fire  01a02706-e024-7485-80f6-93506f777dc5
3           桜色Yell  01a02706-e024-7485-80f6-93516226f055
4         SonoAide  01a02706-e024-7485-80f6-935203870fca

Dados relacionadas a cada música salva, dessa maneira remove as músicas repetidas e mantém as informações diárias para
poder realizar os cálculos.

In [15]:
musicas_pontuacao_dias = ww_2026[['id_musica', 'musica', 'data', 'pontos', 'pts_ganho', 'pts_calc']]

musicas_pontuacao_dias.to_csv('dados/musicas_pontuacao_dias.csv', sep=';', decimal='.', index=False) # Salvando músicas.

# musicas_pontuacao_dias.head()
musicas_pontuacao_dias[musicas_pontuacao_dias['musica'] == 'Usagi Rap'].head(30) # Para conferir se há repetição

,id_musica,musica,data,pontos,pts_ganho,pts_calc
29036,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260725,2534,2534,0.002
29037,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260726,2820,286,0.006
29038,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260727,2818,-2,0.008
29039,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260728,2906,88,0.011
29040,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260729,2903,-3,0.014
29041,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260730,2740,-163,0.017
29042,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260731,2390,-350,0.019
29043,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260801,2276,-114,0.021
29044,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260802,2300,24,0.023
29045,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260803,2472,172,0.026
29046,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260804,2300,-172,0.028
29047,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260805,1125,-92,0.016
29048,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260806,1104,-21,0.017
29049,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260807,1104,0,0.018
29050,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260808,2273,294,0.037
29051,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260809,2318,45,0.040
29052,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260810,2276,-42,0.042
29053,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260811,2341,65,0.044
29054,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260812,2363,22,0.046
29055,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260813,2363,0,0.048
29056,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260814,2211,-152,0.050
29057,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260815,2187,-24,0.053
29058,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260816,2318,131,0.056
29059,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260817,2229,-89,0.058
29060,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260818,2103,-126,0.060
29061,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260820,1041,114,0.031
29087,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260725,2534,2534,0.002
29088,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260726,2820,286,0.006
29089,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260727,2818,-2,0.008
29090,01a02706-e02a-767d-acc3-12e11d878aa8,Usagi Rap,20260728,2906,88,0.011

## Transformando informações das pontuações.

In [16]:
pontuacoes_df = pd.read_csv('dados/musicas_pontuacao_dias.csv', sep=';', decimal='.') # Lendo o `DataFrame` novamente 
                                                                                        # apenas para ter um ponto de 
                                                                                        # parada

pontuacoes_df

,id_musica,musica,data,pontos,pts_ganho,pts_calc
0,01a02706-e024-7485-80f6-934e371aaaae,For us,20260801,2389,2389,0.002
1,01a02706-e024-7485-80f6-934e371aaaae,For us,20260802,1765,-624,0.004
2,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,20260314,1265,1265,0.001
3,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,20260406,1083,1083,0.004
4,01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,20260407,1151,68,0.005
...,...,...,...,...,...,...
50144,01a02706-e024-7485-80f6-948994ca0dcb,Recollect,20260424,1184,1184,0.004
50145,01a02706-e024-7485-80f6-948994ca0dcb,Recollect,20260425,1077,-107,0.006
50146,01a02706-e02d-72a8-bbbd-0644229abe54,Genesis HE★VENS,20260321,858,136,0.005
50147,01a02706-e028-7424-9d5e-11f0a30dc4e4,Voyaging Star's Farewell,20260209,1488,559,0.002
50148,01a02706-e02d-72a8-bbbd-06429371d930,第三个吻痕,20260401,1059,1059,0.001

Agrupando o `DataFrame` por música pois as operações realizadas são por músicas.

In [17]:
pontuacoes_group = pontuacoes_df[['id_musica', 'data', 'pontos', 'pts_ganho', 'pts_calc']].groupby(by=['id_musica'])

pontuacoes_group.head()

,id_musica,data,pontos,pts_ganho,pts_calc
0,01a02706-e024-7485-80f6-934e371aaaae,20260801,2389,2389,0.002
1,01a02706-e024-7485-80f6-934e371aaaae,20260802,1765,-624,0.004
2,01a02706-e024-7485-80f6-934f812b0450,20260314,1265,1265,0.001
3,01a02706-e024-7485-80f6-934f812b0450,20260406,1083,1083,0.004
4,01a02706-e024-7485-80f6-934f812b0450,20260407,1151,68,0.005
...,...,...,...,...,...
50139,01a02706-e02d-72a8-bbbd-0643200f6822,20260427,1206,253,0.005
50140,01a02706-e02d-72a8-bbbd-0643200f6822,20260428,1106,-100,0.006
50141,01a02706-e02d-72a8-bbbd-0643200f6822,20260430,1082,294,0.008
50146,01a02706-e02d-72a8-bbbd-0644229abe54,20260321,858,136,0.005
50148,01a02706-e02d-72a8-bbbd-06429371d930,20260401,1059,1059,0.001

In [18]:
musicas_df = pd.read_csv('dados/musicas.csv', sep=';', decimal='.', index_col='id_musica') # Indice é a música para 
                                                                                            # poder atribuir os valores
                                                                                            # resultantes do `groupby`

musicas_df.head()

                                               musica
id_musica
01a02706-e024-7485-80f6-934e371aaaae           For us
01a02706-e024-7485-80f6-934f812b0450  Sakura-iro Yell
01a02706-e024-7485-80f6-93506f777dc5       We on Fire
01a02706-e024-7485-80f6-93516226f055           桜色Yell
01a02706-e024-7485-80f6-935203870fca         SonoAide

In [19]:
musicas_df['media_pontos'] = pontuacoes_group['pontos'].mean() # Média para utlizar a quantidade de pontos em média.
musicas_df['media_pts_ganho'] = pontuacoes_group['pts_ganho'].mean() # Média para utilizar a quantiade de pontos foram ganhos em média.
musicas_df['total_pts_calc'] = pontuacoes_group['pts_calc'].sum() # Acumulado uma vez que os `pts_calc` é dado por conta dos `pontos` e `pts_ganho`

musicas_df.head()

,musica,media_pontos,media_pts_ganho,total_pts_calc
id_musica,,,,
01a02706-e024-7485-80f6-934e371aaaae,For us,2077.000000,882.500000,0.006
01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,1166.333333,805.333333,0.010
01a02706-e024-7485-80f6-93506f777dc5,We on Fire,1242.500000,525.000000,0.003
01a02706-e024-7485-80f6-93516226f055,桜色Yell,1177.000000,1177.000000,0.001
01a02706-e024-7485-80f6-935203870fca,SonoAide,1439.500000,670.500000,0.005

In [20]:
musicas_df.to_csv('dados/musicas_pontuacao_anual.csv', sep=';', decimal='.')

musicas_df.head()

,musica,media_pontos,media_pts_ganho,total_pts_calc
id_musica,,,,
01a02706-e024-7485-80f6-934e371aaaae,For us,2077.000000,882.500000,0.006
01a02706-e024-7485-80f6-934f812b0450,Sakura-iro Yell,1166.333333,805.333333,0.010
01a02706-e024-7485-80f6-93506f777dc5,We on Fire,1242.500000,525.000000,0.003
01a02706-e024-7485-80f6-93516226f055,桜色Yell,1177.000000,1177.000000,0.001
01a02706-e024-7485-80f6-935203870fca,SonoAide,1439.500000,670.500000,0.005

# Referências

[1] https://stackoverflow.com/questions/33004573/after-groupby-how-to-flatten-column-headers (21/08/2026).

[2] https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html (21/08/2026).