
# Exercício - Compras de Ecommerce  

Neste exercício, você receberá alguns dados falsos sobre algumas compras feitas pela Amazon! Basta seguir as instruções e tente dar melhor para responder as perguntas e completar as tarefas. Sinta-se a vontade para dar uma olhada nas soluções. A maioria das tarefas pode ser resolvida de diferentes maneiras. Para a maior parte, as perguntas ficam cada vez mais difíceis.

Peço desculpas desde já por todos dados que não parecerem muito reais. São todos falsos.

Observe também que todas essas questões podem ser respondidas com uma linha de código.
____
** Importe pandas e leia o arquivo csv "Ecommerce Purchases" e configure-o para um DataFrame chamado ecom. **

In [54]:
import pandas as pd
ecom = pd.read_csv('Ecommerce Purchases') # Arquivo csv baixado do material da vídeo aula e copiado para a mesma
                                            # pasta em que se encontra este `notebook`.

**Verifique o "head" do DataFrame.**

In [55]:
ecom.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

** Quantas linhas e colunas existem? **

In [56]:
# A video aula das soluções mostrou o uso do atributo `shape` para isso
ecom.shape

(10000, 14)

In [57]:
# Para saber quantas linhas (`entries`) e colunas (`columns`) utilizar o método `info`.
ecom.info() # `10000 entries` e `total 14 columns`

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  str
 1   Lot               10000 non-null  str
 2   AM or PM          10000 non-null  str
 3   Browser Info      10000 non-null  str
 4   Company           10000 non-null  str
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  str
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  str
 9   Email             10000 non-null  str
 10  Job               10000 non-null  str
 11  IP Address        10000 non-null  str
 12  Language          10000 non-null  str
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.1 MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

** Qual é o preço de compra médio? **

In [58]:
# Verificar a média da coluna `Purchase Price`
ecom['Purchase Price'].mean() # Número um pouco diferente do que a resposta esperada nos últimas casas decimais. 
                                # mas mesma solução.

np.float64(50.347302)

50.34730200000025

** Quais foram os preços de compra mais altos e mais baixos? **

In [59]:
# Para o preço mais alto utilizar o `max` na coluna `Purchase Price`.
ecom['Purchase Price'].max()

np.float64(99.99)

99.989999999999995

In [60]:
# Para o preço mais baixo utilizar o `min` na coluna `Purchase Price`.
ecom['Purchase Price'].min()

np.float64(0.0)

0.0

** Quantas pessoas têm Inglês 'en' como sua língua de escolha no site? **

In [61]:
# Para mostrar as colunas pode-se acessar o atributo `columns`
ecom.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [62]:
ecom[ecom['Language'] == 'en'].count() # Para condizer com a resposta do `notebook` utilizou-se o `count`.

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

In [63]:
ecom[ecom['Language'] == 'en'].shape # Também pode se utilizar o atributo `shape` e pegar o primeiro elemento 
                                        # segundo a video aula.

(1098, 14)

In [64]:
sum(ecom['Language'] == 'en') # Para isso somar as `serie` resultado do filtro da coluna `Language` igual a `en`.

1098

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
dtype: int64

** Quantas pessoas têm o cargo de "Advogado"? **

In [65]:
# Para condizer com a resposta foi utilizado o método `info` após filtrar o `DataFrame`.
ecom[ecom['Job'] == 'Lawyer'].info()

<class 'pandas.DataFrame'>
Index: 30 entries, 470 to 9979
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           30 non-null     str
 1   Lot               30 non-null     str
 2   AM or PM          30 non-null     str
 3   Browser Info      30 non-null     str
 4   Company           30 non-null     str
 5   Credit Card       30 non-null     int64
 6   CC Exp Date       30 non-null     str
 7   CC Security Code  30 non-null     int64
 8   CC Provider       30 non-null     str
 9   Email             30 non-null     str
 10  Job               30 non-null     str
 11  IP Address        30 non-null     str
 12  Language          30 non-null     str
 13  Purchase Price    30 non-null     float64
dtypes: float64(1), int64(2), str(11)
memory usage: 3.5 KB

In [66]:
# Segundo a video aula pode se utilizar o `shape`.
ecom[ecom['Job'] == 'Lawyer'].shape

(30, 14)

In [67]:
sum(ecom['Job'] == 'Lawyer') # Para advogado foi utiliza o valor `'Lawyer'`.

30

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 470 to 9979
Data columns (total 14 columns):
Address             30 non-null object
Lot                 30 non-null object
AM or PM            30 non-null object
Browser Info        30 non-null object
Company             30 non-null object
Credit Card         30 non-null int64
CC Exp Date         30 non-null object
CC Security Code    30 non-null int64
CC Provider         30 non-null object
Email               30 non-null object
Job                 30 non-null object
IP Address          30 non-null object
Language            30 non-null object
Purchase Price      30 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 3.5+ KB

** Quantas pessoas fizeram a compra durante a AM e quantas pessoas fizeram a compra durante o PM? **

** (Sugestão: Confira [value_counts ()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) **

In [68]:
ecom['AM or PM'].value_counts() # Para isso utilizamos o `value_counts` da coluna `AM or PM`.

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

PM    5068
AM    4932
Name: AM or PM, dtype: int64

** Quais são os 5 títulos de trabalho mais comuns? **

In [69]:
ecom['Job'].value_counts().head() # Utilizando o `head` dessa vez ao invés do indíce :5 após o `value_counts`.

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Designer, jewellery              27
Purchasing manager               27
Name: count, dtype: int64

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

** Alguém fez uma compra que veio do Lot: "90 WT", qual foi o preço de compra para esta transação? **

In [76]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price'] # Ao filtrar o `DataFrame` utilizando a `series` booleana
                                                # como filtro para a notação de colchetes podemos acessar a coluna
                                                # `Purchase Price` para saber o preço da compra desta transação que é de $75.1

513    75.1
Name: Purchase Price, dtype: float64

513    75.1
Name: Purchase Price, dtype: float64

** Qual é o email da pessoa com o seguinte número do cartão de crédito: 4926535242672853 **

In [71]:
# Para isso filtramos o `DataFrame` pela coluna `Credit Card` onde o valor é igual a `4926535242672853` e acessamos a coluna `Email`.
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: str

1234    bondellen@williams-garza.com
Name: Email, dtype: object

** Quantas pessoas têm o American Express como seu fornecedor de cartão de crédito * e * fizeram uma compra acima de US $ 95? **

In [72]:
# Para isso filtramos o `DataFrame` pela coluna `CC Provider` onde o valor é igual a `'American Express'` e também
# pela coluna `Purchase Price` onde o valor é maior que (>) $`95`. 
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [77]:
# Na video aula também utilizou-se o atributo `shape`
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].shape

(39, 14)

In [73]:
# Podemos usar o `sum` na expressão do filtro.
sum((ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95))

39

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

** Difícil: quantas pessoas tem um cartão de crédito que expira em 2025? **

In [74]:
# Para saber se um cartão de crédito expira em 2025 criamos uma função.
def expires_in_2025(cc_exp_date):
    # Verificamos se o ano de expiração é igual a 25. 
    # Para buscar o ano de expiração utilizamos o índice `3:` na `str`
    # que retorna os últimos dois digitos que representam o ano de 
    # expiração do cartão.
    return cc_exp_date[3:] == '25' # Retorna um boolean indicando se expira ou não.

# Testamos a função
assert expires_in_2025('10/25')
assert not expires_in_2025('02/20')

# Utilizamos o `sum` para somar a `série` booleana retornada do método `apply` que recebe 
# a função `expires_in_2025` como parâmetro.
sum(ecom['CC Exp Date'].apply(expires_in_2025))

1033

In [79]:
# Solução da video aula utilizou `lambda`
sum(ecom['CC Exp Date'].apply(lambda x: x[3:]) == '25')

1033

1033

** Difícil: quais são os 5 principais provedores de e-mail / hosts mais populares (por exemplo, gmail.com, yahoo.com, etc ...) **

In [75]:
# Criamos uma função para manipular a coluna `Email` e retornar apenas o provedor do email.
def email_provider(email):
    # Dividimos a `str` através do `@` que separa o nome e provedor do email, e em seguida
    # retornamos o segundo elemento que representa o provedor acessando-o através do índice 1.
    return email.split('@')[1]

# Testa a função email_provider.
assert email_provider('teste@email.com') == 'email.com'

# Para saber os 5 principais emails podemos aplicar a função `email_provider` utilizando o `apply` criando assim
# uma `series` de provedores e através disso utilizar o `value_counts` para contar e ordenar a ocorrência desses
# provedores e por fim utilizar o `head` para trazer apenas os cinco primeiros.
ecom['Email'].apply(email_provider).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

In [80]:
# Solução apresentada na video aula utilizando `lambda` e `iloc`
ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().iloc[:5]

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64