In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn # importa o `randn` diretamente.
np.random.seed(101)

In [3]:
df = pd.DataFrame(randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split()) # Recria o mesmo Dataframe que o
                                                                                        # da última aula.
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Operações no indíce do `DataFrame`

In [4]:
df > 0 # Semelhante as operações em `numpy array`. # Retorna um `DataFrame` com o resultado da operação.

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [5]:
bol = df > 0
df[bol] # No `numpy` retornava um `array` redimensionado aqui os que não atendem recebem `NaN`.=

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
df[df['W'] > 0] # Neste caso ele excluiu a linha C pois ela o valor na coluna W é menor que zero. Diferente do que 
                    # fazer a operação sobre todo o `DataFrame` e utilizar como indíce.

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
# Posso retornar os valores da coluna Y as quais o valor de W é maior que zero. Como se aplicasse um filtro ou uma
# busca no `DataFrame`.
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [8]:
# Código equivalente a `df[df['W'] > 0]['Y']`
bol = df['W'] > 0
df2 = df[bol]
df2['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [9]:
# A palavra chave `and` não consegue lidar com as `series` do `pandas` para fazer a comparação entre `series` 
# utilize o operador `&`.
df[ (df['W'] > 0) & (df['Y'] > 1)] # Filtra onde os valores na coluna W são maiores que 0 E os valores da coluna
                                    # Y são maiores que 1.

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [10]:
df[ (df['W'] > 0) | (df['Y'] > 1)] # Caso queira fazer uma operação `or` entre `series` utiliza o operador `|`

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Resetar o indíce do `DataFrame`

In [11]:
# Para redefinir o indíce utiliza o método `reset_index` 
df.reset_index() # Neste caso o indíce é 0, 1, 2... da mesma forma que é definido o indíce caso não seja informado
                    # o parâmetro `index` na construção do `DataFrame`.
                    # Note também que o indíce que existia anteriormente foi transformado em uma coluna.

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [12]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df.reset_index(inplace=True) # Para que as alterações sejam realizadas no próprio `DataFrame` lembre-se de utilizar
                                # o parâmetro `inplace` como `True`
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [14]:
col = 'RS RJ SP AM SC'.split() # Criando uma nova lista de valores que serão utilizados como indíce no `DataFrame`.
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [15]:
df['Estado'] = col # Adiciona uma nova coluna no `DataFrame` lembrando que ela deve ter o mesmo tamanho que as
                    # linhas do `DataFrame`.
df

  index         W         X         Y         Z Estado
0     A  2.706850  0.628133  0.907969  0.503826     RS
1     B  0.651118 -0.319318 -0.848077  0.605965     RJ
2     C -2.018168  0.740122  0.528813 -0.589001     SP
3     D  0.188695 -0.758872 -0.933237  0.955057     AM
4     E  0.190794  1.978757  2.605967  0.683509     SC

In [16]:
df.set_index('Estado', inplace=True) # Com o método `set_index` ele define a coluna informada como novo indíce do `DataFrame`.
df

       index         W         X         Y         Z
Estado
RS         A  2.706850  0.628133  0.907969  0.503826
RJ         B  0.651118 -0.319318 -0.848077  0.605965
SP         C -2.018168  0.740122  0.528813 -0.589001
AM         D  0.188695 -0.758872 -0.933237  0.955057
SC         E  0.190794  1.978757  2.605967  0.683509