In [1]:
import numpy as np
import pandas as pd

In [4]:
# Níveis de índice
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside)) # o `zip` dentro `list` cria uma lista de `tuple` onde ele associa cada valor
                                        # das listas por indíce.
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [5]:
hier_index = pd.MultiIndex.from_tuples(hier_index) # Desta forma é criado um objeto `MultiIndex` que representa um
                                                    # indíce multi nível.
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [10]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B']) # Instancia um `DataFrame` com o multi indíce criado 
                                                            # anteriormente. Note que há o índice G1 e G2 e dentro
                                                            # dele o índice 1, 2 e 3
df

             A         B
G1 1  0.341615 -0.061182
   2 -1.375157  1.695501
   3  0.881832 -0.296924
G2 1 -0.249433  2.280878
   2  1.291609 -1.710181
   3  0.487699 -0.763188

In [11]:
# Para acessar os valores do `DataFrame` com `MultiIndex` utiliza-se o `loc` com anotações dos colchetes.
df.loc['G1']

          A         B
1  0.341615 -0.061182
2 -1.375157  1.695501
3  0.881832 -0.296924

In [13]:
df.loc['G1'].loc[1] # Agora dentro do grupo G1 utilizamos o `loc` novamente para acessar os valores internos.

A    0.341615
B   -0.061182
Name: 1, dtype: float64

In [15]:
# Os índices possuem nomes, no caso do `DataFrame` `df` não há nomes para eles.
df.index.names # para acessar o nome dos índices.

FrozenList([None, None])

In [17]:
df.index.names = ['Grupo', 'Numero'] # Desta maneira nomeamos ambos os indíces atribuindo a lista no atributo
                                        # `names` dentro de `index`.
df

                     A         B
Grupo Numero
G1    1       0.341615 -0.061182
      2      -1.375157  1.695501
      3       0.881832 -0.296924
G2    1      -0.249433  2.280878
      2       1.291609 -1.710181
      3       0.487699 -0.763188

In [20]:
# `xs` vem de `cross section`
df.xs('G1') # Acessamos o índice G1 através do `xs`

               A         B
Numero
1       0.341615 -0.061182
2      -1.375157  1.695501
3       0.881832 -0.296924

In [26]:
# A diferença do `xs` para o `loc` é que podemos acessar índices internos do `MultiIndex` como por exemplo: 1
df.xs(1, level='Numero') # Acessas o nível `'Numero'` sem precisar acessar o indíce acima que é o `'Grupo'`
                            # Para isso devemos informar o parâmetro `level` com o nome do indíce que queremos 
                            # acessar.
                            # Note que o `DataFrame` possui os indíce externo (`'Grupos'`) mas não o interno
                            # (`'Numero'`) pois ele já foi filtrado pelo `cross section` (`xs`).

              A         B
Grupo
G1     0.341615 -0.061182
G2    -0.249433  2.280878