In [1]:
import numpy as np
import pandas as pd

In [5]:
d = { 'A': [1, 2, np.nan], 'B': [5, np.nan, np.nan], 'C': [1, 2, 3] } # Dicionário com alguns valores ausentes
                                                                        # Valores ausentes são representados por `nan`
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [9]:
df = pd.DataFrame(d) # `DataFrame` com valores faltantes
                        # Valores faltantes pode ser resultante a dados que faltam no banco de dados, problema na 
                        # captação de um sensor, etc
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
df.dropna() # A Saída é um `DataFrame` que exclui os valores `nan`. No caso o `dropna` exclui as linhas que possuem
            # valores `nan`, se colocarmos o `axis` 1 as colunas A e B seriam excluídas ao invés das linhas.

     A    B  C
0  1.0  5.0  1

In [14]:
df.dropna(thresh=2) # Neste caso apenas linhas que possuem pelo menos dois valores faltantes serão removidas,
                    # por conta do paraâmetro `thresh` informado com o valor 2.

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

Da mesma forma que outras operações em pandas o `dropna` possui o parâmetro `inplace`.
```python
df.dropna(thresh=2, inplace=True)
```

In [18]:
df.fillna(value='Fill na') # Com o método `fillna` os valores `nan` podem ser substituídos pelo valor informado 
                            # no parâmetro `value`.

         A        B  C
0      1.0      5.0  1
1      2.0  Fill na  2
2  Fill na  Fill na  3

In [22]:
# Podemos substituir os valores como for convenitente a depender dos dados que estamos analisando.
df['A'].fillna(value=df['A'].mean()) # No caso os valores faltantes na coluna A foram substituídos pela média
                                        # dos valores na coluna A. `fillna` também possui o parâmetro `inplace`.

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [26]:
df.ffill() # Ao utilizar o `ffill` (`forward fill`) preenche os valores `nan` com os valores anteriores da coluna.
            # Na vídeo aula o método utilizado é o `fillna` da seguinte maneira:
            # df.fillna(method='ffill')
            # Ao observar a documentação (shift + tab) do método `fillna` na seção `See also` é citado o método 
            # `ffill`:
            # See Also
            # --------
            # ffill : Fill values by propagating the last valid observation to next valid.

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3