In [1]:
import pandas as pd
# Cria um DataFrame
data = {'Empresa':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'], # Dados utilizados para aula.
        'Nome':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Venda':[200, 120, 340, 123, 243, 350]}

In [2]:
df = pd.DataFrame(data) # Criamos um `DataFrame` com os dados (dicionário) fornecidos
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    123
4      FB     Carl    243
5      FB    Sarah    350

In [3]:
group = df.groupby('Empresa') # Retorna um objeto `pandas.api.typing.DataFrameGroupBy`.
                                # Neste caso o `DataFrame` foi agrupado pela coluna `Empresa`
group

In [4]:
group.sum() # Soma as demais colunas por `Empresa` utilizando o objeto DataFrameGroupBy instanciado anteriormente.

               Nome  Venda
Empresa
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    463

In [5]:
group.mean(numeric_only=True) # Traz a média dos valores da coluna `Venda` agrupado por `Empresa`
                                # Para que não de erro foi utilizado o parâmetro `numeric_only` como `True`
                                # conforme a documentação do `mean` (shift + tab).
                                # O `mean` não foi aplicado para a coluna `Nome` pois ela é uma coluna de texto.

         Venda
Empresa
FB       296.5
GOOG     160.0
MSFT     231.5

In [6]:
group.describe() # O método `describe` traz uma série de informações do agrupamento realizado

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  231.5  153.442172  123.0  177.25  231.5  285.75  340.0

In [7]:
group.count() # `count` Conta a quantidade de valores em cada coluna do agrupamento.

         Nome  Venda
Empresa
FB          2      2
GOOG        2      2
MSFT        2      2

In [8]:
# Agora agrupando pelo nome
group = df.groupby('Nome')
group

In [9]:
group.sum() # Soma o total de vendas de cada `Nome` (ou vendedor) por conta do agrupamento ser feito 
            # através da coluna 'Nome'.

        Empresa  Venda
Nome
Amy        MSFT    340
Carl         FB    243
Charlie    GOOG    120
Sam        GOOG    200
Sarah        FB    350
Vanessa    MSFT    123

In [10]:
group.sum().loc['Amy'] # Com o método `loc` é possível trazer a quantidade de vendas de um 'Nome' em específico.

Empresa    MSFT
Venda       340
Name: Amy, dtype: object