In [5]:
import pandas as pd 
df = pd.DataFrame({'col1': [1, 2, 3, 4], 'col2': [444, 555, 666, 444], 'col3': ['abc', 'def', 'ghi', 'xyz'] })
df.head() # `head` mostra as primeiras 5 linhas do `DataFrame`. Como o indíce não foi informado ele é composto
            # por números inteiros.

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [12]:
df['col2'].unique() # `unique` faz a seleção de dados únicos de uma coluna específica. Traz os dados sem repetir.
                    # semelhante ao `unique` do `numpy` em seguida.

array([444, 555, 666])

In [13]:
import numpy as np
np.unique(df['col2']) # `unique` do `numpy`.

array([444, 555, 666])

In [17]:
len(df['col2'].unique()) # Podemos utilizar o `len` para saber a quantidade (tamanho) de 
                            # dados únicos mas o pandas tem um método próprio chamado `nunique`.
df['col2'].nunique()

3

In [19]:
df['col2'].value_counts() # `value_counts` retorna a quantidade que cada valor aparece no `DataFrame`.

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [22]:
df[ (df['col1'] > 2) & (df['col2'] == 444) ] # Dois filtros em colunas diferentes para seleção de dados no 
                                                # `DataFrame`, podendo utilizar operadores como `==`.

   col1  col2 col3
3     4   444  xyz

In [29]:
def vezes2(x):
    return x * 2

df['col1'].apply(vezes2) # `Com o método `apply` podemos executar funções nas colunas do `DataFrame`
                            # No caso definimos a função `vezes2` e a informamos como parâmetro no `apply`. 
                            # O `apply` funciona como se fosse um `map`.

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [32]:
df['col3'].apply(len) # Podemos utilizar `built in` functions no `apply`. O `apply` aplica uma função
                        # que retorna um valor e recebe um argumento como parâmetro.

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [35]:
df['col1'].apply(lambda x: x*x) # Também podemos passar uma `lambda` ao utilizar o `apply`.

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [36]:
# Para deletar colunas podemos utilizar a função `built in` `del`
del df['col2']
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [38]:
df.columns # Para acessar as colunas existentes no `DataFrame`.

Index(['col1', 'col3'], dtype='str')

In [40]:
df.index # Para acessar o indíce do `DataFrame`. Esse indíce foi inicializado da forma padrão logo o panda utiliza
            # o `RangeIndex`.

RangeIndex(start=0, stop=4, step=1)

In [43]:
# Reiniciando o `DataFrame` conforme a aula.
df = pd.DataFrame({'col1': [1, 2, 3, 4], 'col2': [444, 555, 666, 444], 'col3': ['abc', 'def', 'ghi', 'xyz'] })
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [45]:
df.sort_values(by='col2', inplace=True) # `sort_values` ordena o `DataFrame`, que também disponibilia o 
                                        # parâmetro `inplace`.
df

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [48]:
df.isnull() # `isnull` verifica quais valores do `DataFrame` são nulos.

    col1   col2   col3
0  False  False  False
3  False  False  False
1  False  False  False
2  False  False  False

In [50]:
df.dropna() # `dropna` apaga os valores que são `nan` conforme aulas anteriores.

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [53]:
df = pd.DataFrame({'col1': [1, 2, 3, np.nan],
                    'col2': [np.nan, 555, 666, 444],
                    'col3': ['abc', 'def', 'ghi', 'xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [57]:
df['col1'].fillna(value=df['col1'].mean()) # Podemos popular os valores `nan` utilizando `fillna` conforme 
                                            # aulas anteriores. Também possui o parâmetro `inplace`.

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

#### Sobre o `pivot_table`

In [59]:
data = {'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'], 
    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
    'D': [1, 3, 2, 5, 4, 1]}
df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [63]:
# `pivot_table` funciona de forma semelhante a uma tabela dinâmica do excel. Tu consegue reajustar a visualização
# de seu `DataFrame` e adicionar indíces multi nível.
df.pivot_table(values='D', index=['A', 'B'], columns=['C']) # `pivot_table` possui três parâmetros necessários para seu uso: 
                            # `values`: Os valores de qual coluna quero visualizar (no caso a D).
                            # `index`: Quais colunas quero que funcione como índice. (no caso A e B).
                            # `columns`: Os valores de qual coluna será usado como coluna (no caso C).

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN